-- 031 — NIS2 Reporting Center. A self-contained compliance module: a risk
-- register, control-evidence tracking, security-incident records, generated
-- management reports (snapshotted so progress between reports is measurable),
-- evidence references, and a generic audit log for every change made through the
-- module. All tables are prefixed `blueeye_nis2_*` (+ `blueeye_audit_log`) so the
-- module is cleanly separable. Designed to be extended later (API import,
-- AI recommendations, ticket/asset/monitoring integration) without schema churn.

-- Risk register. risk_score is stored (likelihood * impact, both 1..5) so the API
-- never has to recompute it for filtering/sorting; the route guarantees it stays
-- consistent. management_acceptance records a documented risk-acceptance decision.
CREATE TABLE IF NOT EXISTS blueeye_nis2_risks (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL DEFAULT NULL,
  category VARCHAR(64) NOT NULL,                 -- one of the 10 NIS2 categories
  affected_asset VARCHAR(255) NULL DEFAULT NULL,
  likelihood TINYINT UNSIGNED NOT NULL DEFAULT 1,  -- 1..5
  impact TINYINT UNSIGNED NOT NULL DEFAULT 1,      -- 1..5
  risk_score SMALLINT UNSIGNED NOT NULL DEFAULT 1, -- likelihood * impact (1..25)
  owner VARCHAR(255) NULL DEFAULT NULL,
  status ENUM('open', 'mitigating', 'accepted', 'closed') NOT NULL DEFAULT 'open',
  mitigation_plan TEXT NULL DEFAULT NULL,
  due_date DATE NULL DEFAULT NULL,
  management_acceptance TINYINT(1) NOT NULL DEFAULT 0,
  evidence_link VARCHAR(1024) NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_nis2_risks_status (status),
  KEY idx_nis2_risks_category (category),
  KEY idx_nis2_risks_score (risk_score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Control evidence. A control is a recurring assurance activity tied to a NIS2
-- area. status reflects evidence health (OK / Partial / Missing / Overdue);
-- next_due drives the "overdue" highlighting on the dashboard.
CREATE TABLE IF NOT EXISTS blueeye_nis2_controls (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  control_name VARCHAR(255) NOT NULL,
  nis2_area VARCHAR(64) NOT NULL,
  description TEXT NULL DEFAULT NULL,
  owner VARCHAR(255) NULL DEFAULT NULL,
  frequency ENUM('daily', 'weekly', 'monthly', 'quarterly', 'annually', 'ad-hoc') NOT NULL DEFAULT 'quarterly',
  last_performed DATE NULL DEFAULT NULL,
  next_due DATE NULL DEFAULT NULL,
  evidence_file VARCHAR(1024) NULL DEFAULT NULL,  -- reference/link to stored evidence
  status ENUM('OK', 'Partial', 'Missing', 'Overdue') NOT NULL DEFAULT 'Missing',
  comment TEXT NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_nis2_controls_area (nis2_area),
  KEY idx_nis2_controls_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Security incidents (NIS2 sense — distinct from the network `incidents` table,
-- which is derived from probes). incident_id is a human reference (INC-YYYY-NNNN)
-- generated by the repository. nis2_relevant / notification_required flag the
-- subset that may trigger a regulator notification obligation.
CREATE TABLE IF NOT EXISTS blueeye_nis2_incidents (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  incident_id VARCHAR(32) NOT NULL,
  title VARCHAR(255) NOT NULL,
  severity ENUM('low', 'medium', 'high', 'critical') NOT NULL DEFAULT 'medium',
  detected_at DATETIME NULL DEFAULT NULL,
  started_at DATETIME NULL DEFAULT NULL,
  resolved_at DATETIME NULL DEFAULT NULL,
  affected_systems TEXT NULL DEFAULT NULL,
  business_impact TEXT NULL DEFAULT NULL,
  root_cause TEXT NULL DEFAULT NULL,
  actions_taken TEXT NULL DEFAULT NULL,
  nis2_relevant TINYINT(1) NOT NULL DEFAULT 0,
  notification_required TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('open', 'investigating', 'contained', 'resolved', 'closed') NOT NULL DEFAULT 'open',
  lessons_learned TEXT NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_nis2_incident_ref (incident_id),
  KEY idx_nis2_incidents_severity (severity),
  KEY idx_nis2_incidents_status (status),
  KEY idx_nis2_incidents_detected (detected_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Generated reports. snapshot_json freezes the headline metrics at generation
-- time so the NEXT report can show the delta ("development since last report").
-- A report is a draft until an admin/compliance approver accepts it.
CREATE TABLE IF NOT EXISTS blueeye_nis2_reports (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  report_type ENUM('readiness', 'executive', 'risk', 'control', 'incident') NOT NULL,
  title VARCHAR(255) NOT NULL,
  period_start DATE NULL DEFAULT NULL,
  period_end DATE NULL DEFAULT NULL,
  status ENUM('draft', 'approved') NOT NULL DEFAULT 'draft',
  summary TEXT NULL DEFAULT NULL,
  snapshot_json JSON NULL DEFAULT NULL,
  generated_by INT UNSIGNED NULL DEFAULT NULL,
  generated_by_email VARCHAR(255) NULL DEFAULT NULL,
  approved_by INT UNSIGNED NULL DEFAULT NULL,
  approved_by_email VARCHAR(255) NULL DEFAULT NULL,
  approved_at DATETIME NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_nis2_reports_type (report_type, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Evidence references. A piece of evidence (document/link/screenshot) optionally
-- attached to a control, risk or report. Stored as a reference (file_url) rather
-- than a binary blob so the module needs no object store; the upload route
-- validates + sanitises the reference. Polymorphic link (entity_type/entity_id),
-- so it carries no FK.
CREATE TABLE IF NOT EXISTS blueeye_nis2_evidence (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL DEFAULT NULL,
  file_name VARCHAR(255) NULL DEFAULT NULL,
  file_url VARCHAR(1024) NULL DEFAULT NULL,
  content_type VARCHAR(128) NULL DEFAULT NULL,
  entity_type ENUM('control', 'risk', 'incident', 'report') NULL DEFAULT NULL,
  entity_id INT UNSIGNED NULL DEFAULT NULL,
  uploaded_by INT UNSIGNED NULL DEFAULT NULL,
  uploaded_by_email VARCHAR(255) NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_nis2_evidence_entity (entity_type, entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Generic audit log for the NIS2 module. One row per create/update/delete of a
-- risk, control or incident. old_value/new_value hold JSON snapshots so a change
-- is fully reconstructable. Actor identity is snapshotted (email) so the trail
-- survives user changes. No FK to users for the same reason.
CREATE TABLE IF NOT EXISTS blueeye_audit_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NULL DEFAULT NULL,
  user_email VARCHAR(255) NULL DEFAULT NULL,
  action VARCHAR(32) NOT NULL,                    -- 'create' | 'update' | 'delete' | 'approve'
  entity_type VARCHAR(32) NOT NULL,               -- 'risk' | 'control' | 'incident' | 'report'
  entity_id INT UNSIGNED NULL DEFAULT NULL,
  old_value JSON NULL DEFAULT NULL,
  new_value JSON NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_audit_log_entity (entity_type, entity_id),
  KEY idx_audit_log_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
