-- 096 — MTU fields on probe_results, for the two probes that can see a PMTUD
-- blackhole (blueeye-agent 0.25.x).
--
-- A TCP session that completes its handshake and then stalls the moment real
-- data flows is almost never packet loss. The small packets fit, the first
-- full-size segment does not, some router drops it, and the ICMP
-- "fragmentation needed" that would have told the sender to send smaller is
-- filtered. No probe that only sends small packets can see it, which is why the
-- agent grew two that do:
--
--   `sizes` — the ping size sweep. One entry per payload size the agent sent
--   with don't-fragment set: [{ bytes, sent, recv, lossPct, rttMs, minMs,
--   maxMs, jitterMs, mtuHint, measured, error }]. The row's OWN rtt/loss
--   columns describe the SMALLEST size in the sweep, so a blocked 1472-byte
--   packet never reads as an outage to availability, fleet health or the
--   anomaly detector — only this column carries the size dependence.
--
--   `mtu` — everything the path_mtu probe found, in one object rather than six
--   sparse columns only one probe type would ever fill: { pathMtu,
--   blackholeDetected, recommendedMss, mtuHint, mtuDropAtHop, low, high,
--   overheadBytes, probes: [...], hops: [...] }. `probes` is every packet the
--   binary search sent, because an MTU quoted without the packet that proved it
--   is not evidence. `hops` here is per-hop MTU reachability (respondsSmall /
--   okAtLarge), which is a different measurement from the traceroute latency
--   the existing `hops` column holds — hence its own place inside this object.
--
-- Nullable and backward-compatible: every existing row, and every result from
-- an agent that has not been upgraded, simply leaves both NULL.
ALTER TABLE probe_results
  ADD COLUMN sizes JSON NULL DEFAULT NULL AFTER hops,
  ADD COLUMN mtu JSON NULL DEFAULT NULL AFTER sizes;
