"""License validation, caching, and platform-wide enforcement.

The BlueEye Server is licensed by a separate License Server. On startup and
every 24h the server posts its license key + fingerprint to the License Server,
which returns a signed JWT describing the active tier, agent quota, and
feature set. The JWT is verified against a public key embedded at build time
and cached in the `license_cache` table.

If the License Server is unreachable, the cached payload is honoured for up
to 7 days; after that the installation degrades to the free BlueEye tier.
"""
from __future__ import annotations

import asyncio
import hashlib
import logging
import platform
from datetime import datetime, timedelta, timezone
from typing import Iterable, Optional

import httpx
import jwt
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from .config import settings
from .db import db_session
from .models import Agent, LicenseCache, TestConfig

log = logging.getLogger("blueeye.licensing")


# Embedded at build time. Generated by license_server/scripts/gen_keypair.py.
# Pairs with the LICENSE_PRIVATE_KEY held only by the License Server.
LICENSE_SERVER_PUBLIC_KEY_PEM = """-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAg/aKUBGHWBVgZSwAbT0Zss89pBT6xt/Q8/fXoXA0Uok=
-----END PUBLIC KEY-----
"""

# Test types that require a BlackEye platform license.
BLACKEYE_TEST_TYPES = frozenset({"bgp", "traceroute", "throughput"})

# In-process license state. Each worker maintains its own copy, refreshed by
# the 24h scheduler job (and on first request via load_from_cache).
_state: dict = {}


def _default_state() -> dict:
    return {
        "tier": "blueeye",
        "max_agents": settings.LICENSE_FREE_TIER_MAX_AGENTS,
        "features": [],
        "customer_name": None,
        "expires_at": None,
        "last_verified_at": None,
        "source": "default",
    }


def current_status() -> dict:
    if not _state:
        _state.update(_default_state())
    return dict(_state)


def server_fingerprint() -> str:
    seed = (settings.SECRET_KEY + "|" + platform.node()).encode("utf-8")
    return hashlib.sha256(seed).hexdigest()


def _set_state(payload: dict, source: str) -> None:
    _state.clear()
    _state.update({
        "tier": payload.get("tier", "blueeye"),
        "max_agents": int(payload.get("max_agents") or settings.LICENSE_FREE_TIER_MAX_AGENTS),
        "features": list(payload.get("features") or []),
        "customer_name": payload.get("customer_name"),
        "expires_at": _parse_iso(payload.get("expires_at")),
        "last_verified_at": datetime.now(timezone.utc),
        "source": source,
    })


def _set_degraded() -> None:
    previous_verified = _state.get("last_verified_at")
    _state.clear()
    _state.update({
        "tier": "blueeye",
        "max_agents": settings.LICENSE_FREE_TIER_MAX_AGENTS,
        "features": [],
        "customer_name": None,
        "expires_at": None,
        "last_verified_at": previous_verified,
        "source": "degraded",
    })


def _parse_iso(value: Optional[str]) -> Optional[datetime]:
    if not value:
        return None
    if isinstance(value, datetime):
        return value
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None


def _decode_and_verify(token: str) -> dict:
    return jwt.decode(
        token,
        LICENSE_SERVER_PUBLIC_KEY_PEM,
        algorithms=["EdDSA"],
        options={"require": ["exp"]},
    )


async def load_from_cache(db: AsyncSession) -> bool:
    """Hydrate in-memory state from the cached license. Returns True if a
    cached payload was applied (fresh OR degraded). False means no cache."""
    cached = (await db.execute(select(LicenseCache).where(LicenseCache.id == 1))).scalar_one_or_none()
    if cached is None:
        _state.update(_default_state())
        return False

    cached_at = cached.cached_at
    if cached_at.tzinfo is None:
        cached_at = cached_at.replace(tzinfo=timezone.utc)
    age = datetime.now(timezone.utc) - cached_at

    if age <= timedelta(seconds=settings.LICENSE_GRACE_PERIOD_SECONDS):
        try:
            payload = _decode_and_verify(cached.signature)
        except jwt.PyJWTError as exc:
            log.error("Cached license JWT is invalid (%s); degrading", exc)
            _set_degraded()
            return True
        _set_state(payload, source="cache")
        log.info(
            "License loaded from cache: tier=%s max_agents=%s (cached %s ago)",
            _state["tier"], _state["max_agents"], age,
        )
        return True

    log.warning(
        "Cached license is %s old (> %ss grace); degrading to free tier",
        age, settings.LICENSE_GRACE_PERIOD_SECONDS,
    )
    _set_degraded()
    return True


async def validate_now(db: Optional[AsyncSession] = None) -> dict:
    """Call /v1/license/validate, verify, persist, and update in-memory state.
    Falls back to cache on network or signature failure."""
    own_session = db is None
    if own_session:
        ctx = db_session()
        db = await ctx.__aenter__()
    try:
        if not settings.LICENSE_SERVER_URL or not settings.LICENSE_KEY:
            log.info("Licensing not configured (LICENSE_SERVER_URL or LICENSE_KEY empty); free tier")
            await load_from_cache(db)
            return current_status()

        active_count = await count_active_agents(db)
        body = {
            "license_key": settings.LICENSE_KEY,
            "server_fingerprint": server_fingerprint(),
            "active_agent_count": active_count,
            "version": settings.BLUEEYE_VERSION,
        }
        url = settings.LICENSE_SERVER_URL.rstrip("/") + "/v1/license/validate"
        try:
            async with httpx.AsyncClient(timeout=settings.LICENSE_HTTP_TIMEOUT_SECONDS) as client:
                resp = await client.post(url, json=body)
                resp.raise_for_status()
                data = resp.json()
        except (httpx.HTTPError, ValueError) as exc:
            log.error("License Server unreachable or returned error: %s", exc)
            await load_from_cache(db)
            return current_status()

        token = data.get("license_jwt") or data.get("token")
        if not token:
            log.error("License Server response missing JWT: %r", data)
            await load_from_cache(db)
            return current_status()

        try:
            payload = _decode_and_verify(token)
        except jwt.PyJWTError as exc:
            log.error("License JWT signature/verification failed: %s", exc)
            await load_from_cache(db)
            return current_status()

        await _write_cache(db, payload, token)
        _set_state(payload, source="server")
        log.info(
            "License validated: tier=%s max_agents=%s expires=%s",
            _state["tier"], _state["max_agents"], _state["expires_at"],
        )
        return current_status()
    finally:
        if own_session:
            await ctx.__aexit__(None, None, None)  # type: ignore[possibly-unbound]


async def _write_cache(db: AsyncSession, payload: dict, jwt_token: str) -> None:
    now = datetime.now(timezone.utc)
    existing = await db.get(LicenseCache, 1)
    if existing is None:
        db.add(LicenseCache(id=1, payload_json=payload, signature=jwt_token, cached_at=now))
    else:
        existing.payload_json = payload
        existing.signature = jwt_token
        existing.cached_at = now
    await db.commit()


async def count_active_agents(db: AsyncSession) -> int:
    result = await db.execute(
        select(func.count(Agent.id)).where(Agent.active.is_(True))
    )
    return int(result.scalar_one() or 0)


def check_agent_quota(active_count: int) -> None:
    """Raise HTTPException(402) if over max_agents."""
    from fastapi import HTTPException

    status = current_status()
    if active_count > status["max_agents"]:
        raise HTTPException(
            status_code=402,
            detail=(
                f"License agent quota exceeded: {active_count} active agents "
                f"vs. limit of {status['max_agents']}. Upgrade or revoke agents."
            ),
        )


def filter_test_configs(tests: Iterable[TestConfig]) -> list[TestConfig]:
    """Drop BlackEye-tier tests when the platform license isn't BlackEye."""
    if current_status()["tier"] == "blackeye":
        return list(tests)
    return [t for t in tests if t.test_type not in BLACKEYE_TEST_TYPES]
