'use strict';

// Renders the one-line PowerShell installer served at GET /enroll/:code/install.ps1.
//
// The Windows counterpart of installScript.js. Windows PowerShell cannot run the
// POSIX `curl -sSL <url>/install.sh | sh` one-liner (`curl` is an alias for
// Invoke-WebRequest with different flags, and there is no `sh`), so Windows hosts
// get their own self-contained script fetched with `irm <url>/install.ps1 | iex`.
//
// Like the shell installer it bakes everything in (server URL, cert fingerprint,
// one-time code, expected SHA-256 of the agent SOURCE bundle) and:
//   1. requires Node.js on the host (Windows has no pre-built binary / Docker path
//      by default) — prints a clear message with the download link and stops if absent,
//   2. downloads the agent source from the BlueEye server itself,
//   3. verifies SHA-256 against the embedded checksum (ABORTS on mismatch),
//   4. extracts it with the built-in tar.exe (Windows 10 1803+ / Server 2019+),
//      installs production dependencies with npm,
//   5. enrolls with the embedded one-time code (pinning the cert fingerprint),
//   6. registers a Scheduled Task that runs the agent as SYSTEM at boot and
//      restarts it on failure — the dependency-free Windows equivalent of the
//      systemd unit (no service-wrapper package required).
// It is idempotent (re-running reuses the stored token) and exposes the same
// BLUEEYE_DRY_RUN hook as the shell installer so the download+verify path can be
// exercised without touching the system.
//
// Windows self-update is intentionally NOT wired here: the agent only self-updates
// under systemd (see blueeye-agent runtime.js), so a Windows install is re-run to
// upgrade. That keeps this installer small and avoids a half-working update path.

const { normalizeFingerprint } = require('./fingerprint');

// Single-quote for a PowerShell single-quoted string literal (the only escaping
// PowerShell does inside '...' is doubling an embedded quote). Inputs are already
// constrained (code is base64url, fingerprint hex, serverUrl a validated origin),
// but we quote defensively all the same.
function psSq(value) {
  return String(value == null ? '' : value).replace(/'/g, "''");
}

// A single-line PowerShell prelude that makes the `irm …/install.ps1 | iex`
// bootstrap itself work against an on-prem server: force TLS 1.2 (5.1 defaults to
// TLS 1.0) and, when the cert fingerprint is known, pin the self-signed leaf to
// it so the bootstrap fetch is authenticated (no MITM of install.ps1) rather than
// blindly trusted. Contains NO double quotes, so it embeds safely inside a
// `powershell -Command "…"` argument. Ends with ';' so a fetch can follow.
function winSecurityPrelude(certFingerprint) {
  const tls = '[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor 3072;';
  const fp = normalizeFingerprint(certFingerprint);
  if (!fp) return tls;
  const fpHex = fp.replace(/:/g, '').toLowerCase();
  const pin = `[Net.ServicePointManager]::ServerCertificateValidationCallback = { param($s,$c,$ch,$e) try { ((([Security.Cryptography.SHA256]::Create().ComputeHash($c.GetRawCertData()) | ForEach-Object { $_.ToString('x2') }) -join '') -eq '${fpHex}') } catch { $false } };`;
  return `${tls} ${pin}`;
}

function renderInstallPs1({
  serverUrl,
  code,
  certFingerprint = '',
  sourceSha = '',
  serviceName = 'blueeye-agent',
  agentVersion = '',
} = {}) {
  const fp = normalizeFingerprint(certFingerprint);
  // NB: written to avoid JS template-literal collisions — PowerShell `$var` is
  // fine (only `${` would interpolate in JS, and we never use PS brace-vars), and
  // no backticks are used (PowerShell's line-continuation char clashes with the
  // template literal). Injected values go through psSq() + single quotes.
  return `#Requires -Version 5.1
# BlueEye agent installer (Windows) — generated by blueeye-server. Do not edit by hand.
#
# Run from an ELEVATED PowerShell (Administrator):
#   powershell -NoProfile -ExecutionPolicy Bypass -Command "irm ${psSq(serverUrl)}/enroll/${psSq(code)}/install.ps1 | iex"
#
# Everything needed is embedded below: the server URL, the certificate fingerprint
# to pin, your one-time enrollment code and the expected SHA-256 of the agent
# SOURCE bundle. The agent is downloaded from the BlueEye server itself (no GitHub,
# no registry) and run with native Node.js under a Scheduled Task.
$ErrorActionPreference = 'Stop'

$ServerUrl       = '${psSq(serverUrl)}'
$EnrollCode      = '${psSq(code)}'
$CertFingerprint = '${psSq(fp)}'
$SourceSha256    = '${psSq(sourceSha)}'
$ServiceName     = '${psSq(serviceName)}'
$AgentVersion    = '${psSq(agentVersion)}'

$InstallDir = if ($env:BLUEEYE_INSTALL_DIR) { $env:BLUEEYE_INSTALL_DIR } else { Join-Path $env:ProgramData 'BlueEye\\agent' }
$StateDir   = if ($env:BLUEEYE_STATE_DIR)   { $env:BLUEEYE_STATE_DIR }   else { Join-Path $env:ProgramData 'BlueEye\\state' }
$LogDir     = if ($env:BLUEEYE_LOG_DIR)     { $env:BLUEEYE_LOG_DIR }     else { Join-Path $env:ProgramData 'BlueEye\\logs' }
$TokenPath  = Join-Path $StateDir 'token'
$ConfigPath = Join-Path $StateDir 'config.json'

function Info([string]$m) { Write-Host "[blueeye] $m" }
function Fail([string]$m) { Write-Error "[blueeye] ERROR: $m"; exit 1 }

# Windows PowerShell 5.1 still negotiates TLS 1.0 by default (which a modern
# server rejects) and refuses a self-signed certificate outright — the two most
# common on-prem failures. Force TLS 1.2, and when the server's cert fingerprint
# is known, PIN the self-signed leaf to it (SHA-256 of the DER) instead of
# disabling validation, so integrity is preserved.
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor 3072
$FpHex = ($CertFingerprint -replace '[^0-9A-Fa-f]', '').ToLower()
if ($FpHex) {
  [Net.ServicePointManager]::ServerCertificateValidationCallback = {
    param($psender, $cert, $chain, $sslErrors)
    try {
      $h = [Security.Cryptography.SHA256]::Create().ComputeHash($cert.GetRawCertData())
      ((($h | ForEach-Object { $_.ToString('x2') }) -join '') -eq $FpHex)
    } catch { $false }
  }
}

# Turns a raw Invoke-WebRequest failure into an actionable message (an indicator,
# not a .NET stack): TLS-trust vs unreachable-host vs other.
function Fetch-Or-Explain([string]$url, [string]$outFile) {
  try {
    Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile $outFile
  } catch {
    $m = $_.Exception.Message
    if ($m -match 'trust relationship|SSL/TLS|secure channel|certificate') {
      Fail ("could not verify the server's TLS certificate for $url. On-prem servers usually use a self-signed cert — set its SHA-256 fingerprint on the server (AGENT_CERT_FINGERPRINT) and regenerate the command so the installer can pin it. Details: $m")
    } elseif ($m -match 'Unable to connect|could not be resolved|actively refused|timed out|remote name') {
      Fail ("cannot reach $url from this host — check DNS/firewall, or set BLUEEYE_PUBLIC_URL on the server to an address this machine can actually reach (a bare hostname often will not resolve). Details: $m")
    } else {
      Fail "download failed for $url : $m"
    }
  }
}

if (-not $SourceSha256) {
  Fail 'the BlueEye server has no agent source published — set AGENT_SOURCE_DIR on the server (see docs/enrollment.md), then retry'
}

# Node.js is required (the Windows install has no binary/Docker fallback).
$node = Get-Command node -ErrorAction SilentlyContinue
if (-not $node) {
  Fail ("Node.js was not found on this host. Install Node.js 18+ from https://nodejs.org/ (or 'winget install OpenJS.NodeJS.LTS'), reopen PowerShell, then re-run:" + [Environment]::NewLine +
        "  powershell -NoProfile -ExecutionPolicy Bypass -Command ""irm $ServerUrl/enroll/$EnrollCode/install.ps1 | iex""")
}
$NodeExe = $node.Source

# tar.exe ships in Windows 10 1803+ / Server 2019+; it extracts .tgz directly.
$tar = Get-Command tar.exe -ErrorAction SilentlyContinue
if (-not $tar) {
  Fail 'tar.exe was not found — Windows 10 1803+ or Server 2019+ is required (it provides the built-in tar used to unpack the agent).'
}

$Tmp = Join-Path ([System.IO.Path]::GetTempPath()) ('blueeye-' + [System.IO.Path]::GetRandomFileName())
New-Item -ItemType Directory -Force -Path $Tmp | Out-Null
try {
  $Tarball = Join-Path $Tmp 'agent-source.tgz'
  Info "downloading agent source from $ServerUrl/enroll/agent-source.tgz"
  Fetch-Or-Explain "$ServerUrl/enroll/agent-source.tgz" $Tarball

  $actual = (Get-FileHash -Algorithm SHA256 -Path $Tarball).Hash.ToLower()
  if ($actual -ne $SourceSha256.ToLower()) {
    Fail "checksum mismatch (expected $SourceSha256, got $actual) — refusing to install"
  }
  Info "checksum OK ($SourceSha256)"

  # Inspection/test mode: verified, nothing written to the system yet.
  if ($env:BLUEEYE_DRY_RUN) { Info 'dry-run: verified, stopping before install'; exit 0 }

  # Lay the agent out fresh under the install dir (a re-run replaces the code but
  # keeps the token/config in the separate state dir, so it stays idempotent).
  New-Item -ItemType Directory -Force -Path $InstallDir, $StateDir, $LogDir | Out-Null
  Get-ChildItem -Path $InstallDir -Force -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue

  Info "extracting agent source to $InstallDir"
  & $tar.Source -xzf $Tarball -C $InstallDir
  if ($LASTEXITCODE -ne 0) { Fail 'could not extract the agent source (tar)' }

  $version = $AgentVersion
  if (-not $version) {
    try { $version = (Get-Content (Join-Path $InstallDir 'package.json') -Raw | ConvertFrom-Json).version } catch { $version = 'unknown' }
  }

  Info "installing dependencies (npm) for v$version ..."
  Push-Location $InstallDir
  try {
    # Run npm via cmd.exe with cmd's own 2>&1 merge. npm writes notices/warnings to
    # stderr, and on Windows npm resolves to the npm.ps1 shim: piping its stderr
    # back into PowerShell (2>&1) under $ErrorActionPreference='Stop' turns the very
    # first npm-notice line into a terminating NativeCommandError even on success.
    # Letting cmd merge the streams means PowerShell only sees stdout — no phantom
    # error — and we judge success by the real process exit code.
    $npmOut = & cmd /c 'npm ci --omit=dev 2>&1'
    if ($LASTEXITCODE -ne 0) { $npmOut = & cmd /c 'npm install --omit=dev 2>&1' }
    if ($LASTEXITCODE -ne 0) {
      Info 'npm failed — last lines of its output:'
      $npmOut | Select-Object -Last 25 | ForEach-Object { Write-Host "  $_" }
      Fail 'dependency install failed (npm) — see the npm output above'
    }
  } finally { Pop-Location }

  # Enroll once — idempotent: the agent skips enrollment when a token already
  # exists. Token/config live in the state dir so a re-run/upgrade never loses them.
  Info 'enrolling with the BlueEye server ...'
  $env:BLUEEYE_TOKEN_PATH = $TokenPath
  $env:BLUEEYE_AGENT_CONFIG = $ConfigPath
  $env:BLUEEYE_SERVER_CERT_FINGERPRINT = $CertFingerprint
  $enrollArgs = @((Join-Path $InstallDir 'src\\index.js'), 'enroll', '--code', $EnrollCode, '--server', $ServerUrl)
  if ($CertFingerprint) { $enrollArgs += @('--fingerprint', $CertFingerprint) }
  & $NodeExe @enrollArgs
  if ($LASTEXITCODE -ne 0) { Fail 'enrollment failed' }

  # Launcher .cmd carries the environment the agent needs at boot (a Scheduled
  # Task action cannot set env vars itself) — the Windows analogue of the
  # systemd unit's Environment= lines.
  $launcher = Join-Path $InstallDir 'run-agent.cmd'
  $launcherLines = @(
    '@echo off',
    "set ""BLUEEYE_SERVER_URL=$ServerUrl""",
    "set ""BLUEEYE_SERVER_CERT_FINGERPRINT=$CertFingerprint""",
    "set ""BLUEEYE_TOKEN_PATH=$TokenPath""",
    "set ""BLUEEYE_AGENT_CONFIG=$ConfigPath""",
    "set ""BLUEEYE_ACTION_LOG=$(Join-Path $LogDir 'actions.log')""",
    'set "BLUEEYE_RUNTIME=unmanaged"',
    "cd /d ""$InstallDir""",
    """$NodeExe"" ""$(Join-Path $InstallDir 'src\\index.js')"""
  )
  Set-Content -Path $launcher -Value $launcherLines -Encoding ASCII

  # Register (or replace) a Scheduled Task: run as SYSTEM at startup, restart on
  # failure — the dependency-free equivalent of the systemd service.
  Info "registering scheduled task '$ServiceName' (runs at boot as SYSTEM) ..."
  $action    = New-ScheduledTaskAction -Execute $launcher
  $trigger   = New-ScheduledTaskTrigger -AtStartup
  $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
  $settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit ([TimeSpan]::Zero)
  Register-ScheduledTask -TaskName $ServiceName -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Force | Out-Null
  Start-ScheduledTask -TaskName $ServiceName

  Info "done — agent v$version enrolled and running as scheduled task '$ServiceName'."
  Info "manage it with:  Get-ScheduledTask $ServiceName  |  Stop-ScheduledTask $ServiceName  |  Start-ScheduledTask $ServiceName"
  Info "to remove it later:  Unregister-ScheduledTask -TaskName $ServiceName -Confirm:\$false ; Remove-Item -Recurse -Force '$InstallDir','$StateDir'"
} finally {
  Remove-Item -Recurse -Force $Tmp -ErrorAction SilentlyContinue
}
`;
}

module.exports = { renderInstallPs1, winSecurityPrelude };
