'use strict';

// Renders the one-line installer served at GET /enroll/:code/install.sh.
//
// No pre-built binaries are involved. The script is self-contained (server URL,
// certificate fingerprint, enrollment code and the SHA-256 of the agent SOURCE
// bundle are baked in). It:
//   1. downloads the agent source from the BlueEye server itself,
//   2. verifies SHA-256 against the embedded checksum (ABORTS on mismatch),
//   3. picks a runtime — pre-built binary by DEFAULT when the server has built one
//      (no Node.js or Docker required); then native Node + systemd; then Docker
//      (auto-detected — slim image when binary available, otherwise node:22-alpine);
//      if no runtime is available it prints clear instructions and stops — never dead-ends,
//   4. for native installs (binary or node) lays the agent out in the versioned
//      releases/<v> + `current` symlink layout (state in /var/lib, logs in
//      /var/log) so signed self-updates can swap releases atomically with rollback,
//   5. fetches the release public key from the server and pins it, so SIGNED
//      self-updates verify with no manual key provisioning,
//   6. enrolls with the embedded one-time code (pinning the cert fingerprint).
// It is idempotent (re-running reuses the stored token) and exposes a few env
// hooks (BLUEEYE_CURL, BLUEEYE_SHA256, BLUEEYE_RUNTIME, BLUEEYE_DRY_RUN) so the
// verification path can be exercised in tests without touching the system.

const { normalizeFingerprint } = require('./fingerprint');

// Shell-quote for a double-quoted context (the inputs are server-controlled and
// already constrained — code is base64url, fingerprint is hex, serverUrl is a
// validated origin — but we quote defensively all the same).
function shDq(value) {
  return String(value == null ? '' : value).replace(/(["\\$`])/g, '\\$1');
}

function renderInstallScript({
  serverUrl,
  code,
  certFingerprint = '',
  sourceSha = '',
  serviceName = 'blueeye-agent',
  // SHA-256 of each pre-built binary (empty string = not built yet).
  binaryChecksums = {},
  // Agent version string (embedded so the binary release dir is named properly).
  agentVersion = '',
} = {}) {
  const fp = normalizeFingerprint(certFingerprint);
  const binX64   = shDq(binaryChecksums['linux-x64']   || '');
  const binArm64 = shDq(binaryChecksums['linux-arm64'] || '');
  const ver      = shDq(agentVersion || '');
  return `#!/bin/sh
# BlueEye agent installer — generated by blueeye-server. Do not edit by hand.
#
# Everything needed is embedded below: the server URL, the certificate
# fingerprint to pin, your one-time enrollment code and the expected SHA-256 of
# the agent SOURCE bundle. The agent is downloaded from the BlueEye server itself
# (no GitHub, no registry — works on air-gapped networks, as long as the machine
# can reach the server) and installed via the lightest runtime available:
#   1. pre-built binary  (~60 MB, no Node.js or Docker needed) — default when ready
#   2. native Node.js + systemd — fallback when Node is present
#   3. Docker (auto)    — slim image (~120 MB) if binary ready, else node:22-alpine (~500 MB)
set -eu

SERVER_URL="${shDq(serverUrl)}"
ENROLL_CODE="${shDq(code)}"
CERT_FINGERPRINT="${shDq(fp)}"
SOURCE_SHA256="${shDq(sourceSha)}"
SERVICE_NAME="${shDq(serviceName)}"
AGENT_VERSION="${ver}"
BINARY_SHA_LINUX_X64="${binX64}"
BINARY_SHA_LINUX_ARM64="${binArm64}"
INSTALL_DIR="\${BLUEEYE_INSTALL_DIR:-/opt/blueeye-agent}"
STATE_DIR="\${BLUEEYE_STATE_DIR:-/var/lib/blueeye-agent}"
LOG_DIR="\${BLUEEYE_LOG_DIR:-/var/log/blueeye-agent}"
IMAGE="\${BLUEEYE_IMAGE:-blueeye-agent}"
CONTAINER="\${BLUEEYE_CONTAINER:-blueeye-agent}"
TOKEN_VOLUME="\${BLUEEYE_TOKEN_VOLUME:-blueeye-agent-data}"

# Test/override hooks (unset in normal use).
CURL="\${BLUEEYE_CURL:-curl}"
SHA256="\${BLUEEYE_SHA256:-}"
RUNTIME="\${BLUEEYE_RUNTIME:-}"   # force binary|docker|node|none (default: auto)

log()  { printf '[blueeye] %s\\n' "$*"; }
fail() { printf '[blueeye] ERROR: %s\\n' "$*" >&2; exit 1; }

pick_sha_tool() {
  [ -n "$SHA256" ] && return 0
  if command -v sha256sum >/dev/null 2>&1; then SHA256="sha256sum";
  elif command -v shasum >/dev/null 2>&1; then SHA256="shasum -a 256";
  else fail "no SHA-256 tool found (need sha256sum or shasum)"; fi
}

# Returns the arch slug that matches this host, or empty on unsupported arch.
# The pre-built binaries are Linux-only, so a non-Linux kernel (e.g. macOS, whose
# uname -m is also x86_64/arm64) must NOT match one — it would download a Linux
# executable and fail to run. macOS/other kernels fall through to node/docker.
pick_binary_arch() {
  [ "$(uname -s)" = "Linux" ] || { printf ''; return 0; }
  case "$(uname -m)" in
    x86_64|amd64)  printf '%s' "linux-x64"  ;;
    aarch64|arm64) printf '%s' "linux-arm64" ;;
    *)             printf ''                  ;;
  esac
}

# Returns the embedded binary SHA-256 for this host's arch, or empty.
pick_binary_sha() {
  [ "$(uname -s)" = "Linux" ] || { printf ''; return 0; }
  case "$(uname -m)" in
    x86_64|amd64)  printf '%s' "$BINARY_SHA_LINUX_X64"  ;;
    aarch64|arm64) printf '%s' "$BINARY_SHA_LINUX_ARM64" ;;
    *)             printf ''                              ;;
  esac
}

# Point the \`current\` symlink at $1 (a release dir). On Linux we stage the new
# link then rename it over the old one — an atomic replace (mv -T needs GNU mv).
# BSD/macOS mv has no -T (and would move INTO the target dir), so there we replace
# the symlink directly; still effectively instantaneous for a symlink swap.
point_current() {
  DEST_LINK="$1"
  if [ "$(uname -s)" = "Darwin" ]; then
    rm -f "$CURRENT" && ln -sfn "$DEST_LINK" "$CURRENT" || fail "could not point current -> $DEST_LINK"
  else
    ln -sfn "$DEST_LINK" "$CURRENT.next" && mv -T "$CURRENT.next" "$CURRENT" || fail "could not point current -> $DEST_LINK"
  fi
}

main() {
  [ -n "$SOURCE_SHA256" ] || fail "the BlueEye server has no agent source published — set AGENT_SOURCE_DIR on the server (see docs/enrollment.md), then retry"

  TMP=$(mktemp -d)
  trap 'rm -rf "$TMP"' EXIT
  TARBALL="$TMP/agent-source.tgz"

  log "downloading agent source from $SERVER_URL/enroll/agent-source.tgz"
  $CURL -fsSL "$SERVER_URL/enroll/agent-source.tgz" -o "$TARBALL" || fail "download failed"

  pick_sha_tool
  ACTUAL=$($SHA256 "$TARBALL" | awk '{print $1}')
  if [ "$ACTUAL" != "$SOURCE_SHA256" ]; then
    fail "checksum mismatch (expected $SOURCE_SHA256, got $ACTUAL) — refusing to install"
  fi
  log "checksum OK ($SOURCE_SHA256)"

  # Stop here in test/inspection mode — nothing has been written to the system.
  if [ -n "\${BLUEEYE_DRY_RUN:-}" ]; then log "dry-run: verified, stopping before install"; exit 0; fi

  # Pick a runtime. Priority order (unless BLUEEYE_RUNTIME overrides):
  #   binary  — pre-built self-contained executable; no Node.js or Docker needed
  #   node    — native Node.js + systemd
  #   docker  — containerised; auto when Docker is found and no better runtime is available
  #   none    — nothing available; print instructions and exit
  if [ -z "$RUNTIME" ]; then
    BINARY_SHA=$(pick_binary_sha)
    if [ -n "$BINARY_SHA" ]; then
      RUNTIME=binary
    elif command -v node >/dev/null 2>&1; then
      RUNTIME=node
    elif command -v docker >/dev/null 2>&1; then
      RUNTIME=docker
    else
      RUNTIME=none
    fi
  fi
  if [ "$RUNTIME" = "docker" ] && ! command -v docker >/dev/null 2>&1; then
    fail "Docker runtime selected but Docker is not installed on this host.
  - install Docker:  https://docs.docker.com/engine/install/
  - or install Node.js for a native install:  https://nodejs.org/"
  fi
  if [ "$RUNTIME" = "none" ]; then
    fail "Node.js was not found on this host — no compatible runtime available.
Install one of the following and re-run:
  - pre-built binary:  retry once the server has finished building (check agent-binary-status)
  - Node.js 18+:       https://nodejs.org/
  - Docker:            https://docs.docker.com/engine/install/
then:  curl -sSL $SERVER_URL/enroll/$ENROLL_CODE/install.sh | sh"
  fi
  log "runtime: $RUNTIME"

  [ "$(id -u)" = "0" ] || fail "installation needs root — re-run with sudo, e.g.  curl -sSL <url> | sudo sh"

  if   [ "$RUNTIME" = "binary" ]; then install_binary "$TARBALL"
  elif [ "$RUNTIME" = "docker" ]; then install_docker "$TARBALL"
  else                                  install_node   "$TARBALL"
  fi
  run_doctor
  log "to remove the agent later: curl -sSL $SERVER_URL/enroll/uninstall.sh | sudo sh"
}

# Connection self-test after install: run the agent's built-in \`doctor\` so the
# install ends with a CONNECTED / NOT-CONNECTED verdict + fix suggestions instead
# of a silent success. Informational only — never fails the install (|| true); an
# older agent source without 'doctor' just prints usage.
run_doctor() {
  log "running connection self-test (blueeye-agent doctor) ..."
  DOC_ENV="BLUEEYE_TOKEN_PATH=$TOKEN_PATH BLUEEYE_AGENT_CONFIG=$CONFIG_PATH BLUEEYE_SERVER_URL=$SERVER_URL BLUEEYE_SERVER_CERT_FINGERPRINT=$CERT_FINGERPRINT"
  case "$RUNTIME" in
    node)   env $DOC_ENV node "$CURRENT/src/index.js" doctor || true ;;
    binary) env $DOC_ENV "$CURRENT/blueeye-agent" doctor || true ;;
    docker) docker exec "$CONTAINER" node src/index.js doctor || true ;;
  esac
}

install_binary() {
  TARBALL_PATH="$1"
  BINARY_ARCH=$(pick_binary_arch)
  BINARY_SHA=$(pick_binary_sha)
  [ -n "$BINARY_ARCH" ] || fail "unsupported architecture '$(uname -m)' for binary install"
  [ -n "$BINARY_SHA"  ] || fail "no binary SHA for this arch — re-run install.sh (the server may still be building)"

  RELEASES="$INSTALL_DIR/releases"
  CURRENT="$INSTALL_DIR/current"
  TOKEN_PATH="$STATE_DIR/token"
  CONFIG_PATH="$STATE_DIR/config.json"
  mkdir -p "$RELEASES" "$STATE_DIR" "$LOG_DIR"

  # Stage binary, verify, move into versioned release dir.
  STAGE="$RELEASES/.stage.$$"
  rm -rf "$STAGE"; mkdir -p "$STAGE"

  log "downloading pre-built agent binary ($BINARY_ARCH) ..."
  $CURL -fsSL "$SERVER_URL/enroll/agent-binary/$BINARY_ARCH" -o "$STAGE/blueeye-agent" \\
    || fail "binary download failed"
  chmod +x "$STAGE/blueeye-agent"

  ACTUAL_BIN=$($SHA256 "$STAGE/blueeye-agent" | awk '{print $1}')
  [ "$ACTUAL_BIN" = "$BINARY_SHA" ] \\
    || fail "binary checksum mismatch (expected $BINARY_SHA, got $ACTUAL_BIN)"
  log "binary checksum OK"

  DEST="$RELEASES/\${AGENT_VERSION:-$(date +%Y%m%d%H%M%S)}"
  rm -rf "$DEST"; mv "$STAGE" "$DEST"

  # Fetch the release trust anchor (same as the node install path).
  RELEASE_KEY=$($CURL -fsSL "$SERVER_URL/enroll/agent-release-key" 2>/dev/null || true)

  # Enroll once (idempotent: skipped when a token already exists).
  FP_ARG=""
  [ -n "$CERT_FINGERPRINT" ] && FP_ARG="--fingerprint $CERT_FINGERPRINT"
  # shellcheck disable=SC2086
  BLUEEYE_TOKEN_PATH="$TOKEN_PATH" BLUEEYE_AGENT_CONFIG="$CONFIG_PATH" \\
  BLUEEYE_SERVER_CERT_FINGERPRINT="$CERT_FINGERPRINT" \\
    "$DEST/blueeye-agent" enroll --code "$ENROLL_CODE" --server "$SERVER_URL" $FP_ARG \\
    || fail "enrollment failed"

  point_current "$DEST"

  install_service "$CURRENT/blueeye-agent" binary
  log "done — agent v\${AGENT_VERSION:-?} enrolled and running (binary)"
}

install_docker() {
  TARBALL_PATH="$1"
  mkdir -p "$INSTALL_DIR"
  log "extracting agent source to $INSTALL_DIR"
  tar -xzf "$TARBALL_PATH" -C "$INSTALL_DIR" || fail "could not extract the agent source"

  # If the server has a pre-built binary and Dockerfile.slim is present, use the
  # slim image (debian:12-slim + binary ≈ 120 MB) instead of node:22-alpine (≈ 500 MB).
  BINARY_ARCH=$(pick_binary_arch)
  BINARY_SHA=$(pick_binary_sha)
  SLIM_DOCKERFILE="$INSTALL_DIR/Dockerfile.slim"
  USE_SLIM=0
  if [ -n "$BINARY_ARCH" ] && [ -n "$BINARY_SHA" ] && [ -f "$SLIM_DOCKERFILE" ]; then
    log "downloading pre-built binary for slim Docker image ($BINARY_ARCH) ..."
    if $CURL -fsSL "$SERVER_URL/enroll/agent-binary/$BINARY_ARCH" -o "$INSTALL_DIR/blueeye-agent-linux" 2>/dev/null; then
      ACTUAL_BIN=$($SHA256 "$INSTALL_DIR/blueeye-agent-linux" | awk '{print $1}')
      if [ "$ACTUAL_BIN" = "$BINARY_SHA" ]; then
        USE_SLIM=1
        log "binary checksum OK — using slim image (saves ~380 MB)"
      else
        log "binary checksum mismatch — falling back to node:22-alpine image"
        rm -f "$INSTALL_DIR/blueeye-agent-linux"
      fi
    else
      log "binary download failed — falling back to node:22-alpine image"
    fi
  fi

  if [ "$USE_SLIM" = "1" ]; then
    log "building slim image $IMAGE ..."
    docker build -t "$IMAGE" -f "$SLIM_DOCKERFILE" "$INSTALL_DIR" >/dev/null || fail "docker build (slim) failed"
  else
    log "building image $IMAGE (this can take a minute) ..."
    docker build -t "$IMAGE" "$INSTALL_DIR" >/dev/null || fail "docker build failed"
  fi

  docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
  docker volume create "$TOKEN_VOLUME" >/dev/null
  FP_ENV=""
  [ -n "$CERT_FINGERPRINT" ] && FP_ENV="-e BLUEEYE_SERVER_CERT_FINGERPRINT=$CERT_FINGERPRINT"
  # Host networking so the agent sees the host's real interfaces. The agent
  # enrolls itself on first start from BLUEEYE_ENROLLMENT_CODE; the token lives on
  # the named volume, so re-runs are idempotent (the code is then ignored).
  # shellcheck disable=SC2086
  docker run -d --name "$CONTAINER" --restart unless-stopped --network host \\
    -e "BLUEEYE_SERVER_URL=$SERVER_URL" \\
    -e "BLUEEYE_ENROLLMENT_CODE=$ENROLL_CODE" \\
    -e "BLUEEYE_TOKEN_PATH=/data/token" \\
    -e "BLUEEYE_RUNTIME=docker" \\
    $FP_ENV \\
    -v "$TOKEN_VOLUME:/data" \\
    "$IMAGE" >/dev/null || fail "docker run failed"
  log "done — agent running as docker container '$CONTAINER'  (docker logs -f $CONTAINER)"
}

install_node() {
  TARBALL_PATH="$1"
  command -v node >/dev/null 2>&1 || fail "Node not found"
  command -v npm  >/dev/null 2>&1 || fail "npm is required to install the agent's dependencies (or use Docker: BLUEEYE_RUNTIME=docker)"
  NODE_BIN=$(command -v node)

  RELEASES="$INSTALL_DIR/releases"
  CURRENT="$INSTALL_DIR/current"
  TOKEN_PATH="$STATE_DIR/token"
  CONFIG_PATH="$STATE_DIR/config.json"
  mkdir -p "$RELEASES" "$STATE_DIR" "$LOG_DIR"

  # Stage the verified bundle INSIDE releases/ (same filesystem, so the final
  # rename is atomic), read its version, then place it as releases/<version>.
  STAGE="$RELEASES/.stage.$$"
  rm -rf "$STAGE"; mkdir -p "$STAGE"
  tar -xzf "$TARBALL_PATH" -C "$STAGE" || { rm -rf "$STAGE"; fail "could not extract the agent source"; }
  VERSION=$(node -p "require('$STAGE/package.json').version" 2>/dev/null || true)
  [ -n "$VERSION" ] || VERSION="source-$(date +%Y%m%d%H%M%S)"
  DEST="$RELEASES/$VERSION"
  rm -rf "$DEST"; mv "$STAGE" "$DEST"

  log "installing dependencies (npm) for v$VERSION ..."
  ( cd "$DEST" && { npm ci --omit=dev >/dev/null 2>&1 || npm install --omit=dev >/dev/null 2>&1; } ) || fail "dependency install failed"

  # Atomic blue/green: point \`current\` at the new release (rename over a symlink
  # is atomic on POSIX), so a later signed update swaps releases the same way.
  point_current "$DEST"

  # Fetch the release trust anchor (Ed25519 public key) from the server so SIGNED
  # self-updates verify automatically — no manual key provisioning. Not secret;
  # optional (older server / unconfigured key -> 404 -> empty, unsigned-only).
  RELEASE_KEY=$($CURL -fsSL "$SERVER_URL/enroll/agent-release-key" 2>/dev/null || true)

  # Enroll once (idempotent: skipped when a token already exists), writing the
  # token to the SHARED state dir so a release swap never loses it.
  FP_ARG=""
  [ -n "$CERT_FINGERPRINT" ] && FP_ARG="--fingerprint $CERT_FINGERPRINT"
  # shellcheck disable=SC2086
  BLUEEYE_TOKEN_PATH="$TOKEN_PATH" BLUEEYE_AGENT_CONFIG="$CONFIG_PATH" BLUEEYE_SERVER_CERT_FINGERPRINT="$CERT_FINGERPRINT" \\
    node "$CURRENT/src/index.js" enroll --code "$ENROLL_CODE" --server "$SERVER_URL" $FP_ARG \\
    || fail "enrollment failed"

  install_service "$NODE_BIN $CURRENT/src/index.js" systemd
  log "done — agent v$VERSION enrolled and running (node + systemd)"
}

# install_launchd EXEC_START RUNTIME_TAG
# macOS service install: writes a LaunchDaemon plist that runs the agent from the
# \`current\` symlink and reloads it. Env mirrors the systemd unit so token/config/
# logs live outside the swappable release dir. Label: com.blueeye.agent.
install_launchd() {
  EXEC_START="$1"
  RUNTIME_TAG="\${2:-launchd}"
  LABEL="com.blueeye.agent"
  PLIST="/Library/LaunchDaemons/$LABEL.plist"

  {
    printf '%s\\n' '<?xml version="1.0" encoding="UTF-8"?>'
    printf '%s\\n' '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
    printf '%s\\n' '<plist version="1.0"><dict>'
    printf '  <key>Label</key><string>%s</string>\\n' "$LABEL"
    printf '%s\\n' '  <key>ProgramArguments</key><array>'
    # EXEC_START is a space-joined command (e.g. "/usr/local/bin/node /opt/.../src/index.js");
    # the install paths we control have no spaces, so word-splitting is safe here.
    # shellcheck disable=SC2086
    for arg in $EXEC_START; do printf '    <string>%s</string>\\n' "$arg"; done
    printf '%s\\n' '  </array>'
    printf '  <key>WorkingDirectory</key><string>%s</string>\\n' "$CURRENT"
    printf '%s\\n' '  <key>EnvironmentVariables</key><dict>'
    printf '    <key>BLUEEYE_SERVER_URL</key><string>%s</string>\\n' "$SERVER_URL"
    printf '    <key>BLUEEYE_SERVER_CERT_FINGERPRINT</key><string>%s</string>\\n' "$CERT_FINGERPRINT"
    printf '    <key>BLUEEYE_TOKEN_PATH</key><string>%s</string>\\n' "$TOKEN_PATH"
    printf '    <key>BLUEEYE_AGENT_CONFIG</key><string>%s</string>\\n' "$CONFIG_PATH"
    printf '    <key>BLUEEYE_ACTION_LOG</key><string>%s</string>\\n' "$LOG_DIR/actions.log"
    printf '    <key>BLUEEYE_RELEASES_DIR</key><string>%s</string>\\n' "$RELEASES"
    printf '    <key>BLUEEYE_CURRENT_LINK</key><string>%s</string>\\n' "$CURRENT"
    printf '    <key>BLUEEYE_RUNTIME</key><string>%s</string>\\n' "$RUNTIME_TAG"
    printf '    <key>BLUEEYE_SERVICE_NAME</key><string>%s</string>\\n' "$SERVICE_NAME"
    printf '%s\\n' '  </dict>'
    printf '%s\\n' '  <key>RunAtLoad</key><true/>'
    printf '%s\\n' '  <key>KeepAlive</key><true/>'
    printf '  <key>StandardOutPath</key><string>%s</string>\\n' "$LOG_DIR/agent.log"
    printf '  <key>StandardErrorPath</key><string>%s</string>\\n' "$LOG_DIR/agent.err.log"
    printf '%s\\n' '</dict></plist>'
  } > "$PLIST" || fail "could not write $PLIST"

  # Reload: bootout the old daemon (ignored if not loaded) then bootstrap the new
  # one. Fall back to legacy load/unload on older macOS without bootstrap.
  if launchctl bootstrap system "$PLIST" 2>/dev/null; then
    launchctl kickstart -k "system/$LABEL" 2>/dev/null || true
  else
    launchctl unload "$PLIST" 2>/dev/null || true
    launchctl load -w "$PLIST" || fail "launchctl load failed"
  fi
  log "launchd daemon $LABEL loaded (starts at boot; manage with: sudo launchctl print system/$LABEL)"
}

# install_service EXEC_START RUNTIME_TAG
# Installs (or reinstalls) the systemd unit that runs the agent.
# EXEC_START — the full ExecStart value (e.g. "/opt/.../blueeye-agent" or "node .../src/index.js")
# RUNTIME_TAG — value for BLUEEYE_RUNTIME env var in the unit
install_service() {
  EXEC_START="$1"
  RUNTIME_TAG="\${2:-systemd}"

  # macOS: run under launchd as a LaunchDaemon (starts at boot, KeepAlive restarts
  # on exit) — the platform-native equivalent of the systemd unit. Label matches
  # the server's connection-diagnosis hints (system/com.blueeye.agent).
  if [ "$(uname -s)" = "Darwin" ]; then
    install_launchd "$EXEC_START" "$RUNTIME_TAG"
    return $?
  fi

  if ! command -v systemctl >/dev/null 2>&1; then
    log "systemd not found — start the agent manually:"
    log "  $EXEC_START"
    return 0
  fi
  UNIT="/etc/systemd/system/$SERVICE_NAME.service"
  # Runs from the \`current\` symlink so a signed update can swap the release dir
  # underneath atomically. Token/config/log live OUTSIDE the swappable release dir
  # so updates never touch them.
  cat > "$UNIT" <<UNIT_EOF
[Unit]
Description=BlueEye monitoring agent
Documentation=https://github.com/gudlever-lgtm/blueeye-agent
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=120
StartLimitBurst=5

[Service]
Type=simple
WorkingDirectory=$CURRENT
ExecStart=$EXEC_START
Restart=on-failure
RestartSec=5
Environment=BLUEEYE_SERVER_URL=$SERVER_URL
Environment=BLUEEYE_SERVER_CERT_FINGERPRINT=$CERT_FINGERPRINT
Environment=BLUEEYE_TOKEN_PATH=$TOKEN_PATH
Environment=BLUEEYE_AGENT_CONFIG=$CONFIG_PATH
Environment=BLUEEYE_ACTION_LOG=$LOG_DIR/actions.log
Environment=BLUEEYE_RELEASES_DIR=$RELEASES
Environment=BLUEEYE_CURRENT_LINK=$CURRENT
Environment=BLUEEYE_RUNTIME=$RUNTIME_TAG
Environment=BLUEEYE_SERVICE_NAME=$SERVICE_NAME

[Install]
WantedBy=multi-user.target
UNIT_EOF

  # Release trust anchor as a drop-in (base64 keeps the multi-line PEM on a single
  # Environment= line; the agent decodes base64-of-PEM). Only when the server gave
  # us a key — otherwise signed self-updates need BLUEEYE_RELEASE_PUBLIC_KEY set by hand.
  if [ -n "$RELEASE_KEY" ] && command -v base64 >/dev/null 2>&1; then
    mkdir -p "$UNIT.d"
    KEY_B64=$(printf '%s' "$RELEASE_KEY" | base64 | tr -d '\\n')
    {
      echo "[Service]"
      printf 'Environment=BLUEEYE_RELEASE_PUBLIC_KEY=%s\\n' "$KEY_B64"
    } > "$UNIT.d/10-release-key.conf"
    log "signed self-updates enabled (release key pinned)"
  elif [ -n "$RELEASE_KEY" ]; then
    log "note: 'base64' missing — set BLUEEYE_RELEASE_PUBLIC_KEY manually for signed self-updates"
  else
    log "note: server published no release key — signed self-updates need BLUEEYE_RELEASE_PUBLIC_KEY set manually"
  fi

  systemctl daemon-reload
  systemctl enable "$SERVICE_NAME" >/dev/null 2>&1 || true
  systemctl restart "$SERVICE_NAME"
  log "service $SERVICE_NAME enabled and (re)started"
}

main "$@"
`;
}

module.exports = { renderInstallScript };
