'use strict';

// Renders the one-line installer served at GET /enroll/:code/install.sh.
//
// The script is fully self-contained: server URL, certificate fingerprint, the
// enrollment code and a per-platform SHA-256 checksum table are baked in. It
//   1. detects the platform (uname),
//   2. downloads the matching binary from the BlueEye server itself,
//   3. verifies SHA-256 against the embedded checksum (ABORTS on mismatch),
//   4. installs the binary and runs `blueeye-agent enroll --code …`,
//   5. installs + starts a systemd service.
// It is idempotent (re-running won't double-install) and exposes a few env
// hooks (BLUEEYE_CURL, BLUEEYE_SHA256, BLUEEYE_PLATFORM, BLUEEYE_DRY_RUN) so the
// verification path can be exercised in tests without touching the system.

const { normalizeFingerprint } = require('./fingerprint');

// Shell-quote for a double-quoted context (the inputs are server-controlled and
// already constrained — code is base64url, fingerprint is hex, serverUrl is a
// validated origin — but we quote defensively all the same).
function shDq(value) {
  return String(value == null ? '' : value).replace(/(["\\$`])/g, '\\$1');
}

function checksumCase(checksums) {
  const arms = Object.keys(checksums)
    .sort()
    .map((slug) => `    ${slug}) printf '%s' "${shDq(checksums[slug])}" ;;`);
  arms.push("    *) printf '' ;;");
  return arms.join('\n');
}

function renderInstallScript({
  serverUrl,
  code,
  certFingerprint = '',
  checksums = {},
  binName = 'blueeye-agent',
  serviceName = 'blueeye-agent',
} = {}) {
  const fp = normalizeFingerprint(certFingerprint);
  return `#!/bin/sh
# BlueEye agent installer — generated by blueeye-server. Do not edit by hand.
#
# Everything needed is embedded below: the server URL, the certificate
# fingerprint to pin, your one-time enrollment code and the expected SHA-256 of
# the agent binary. The binary is downloaded from the BlueEye server itself, so
# this also works on networks without Internet access (air-gapped), as long as
# the machine can reach the server.
set -eu

SERVER_URL="${shDq(serverUrl)}"
ENROLL_CODE="${shDq(code)}"
CERT_FINGERPRINT="${shDq(fp)}"
BIN_NAME="${shDq(binName)}"
SERVICE_NAME="${shDq(serviceName)}"
INSTALL_DIR="\${BLUEEYE_INSTALL_DIR:-/opt/blueeye-agent}"

# Test/override hooks (unset in normal use).
CURL="\${BLUEEYE_CURL:-curl}"
SHA256="\${BLUEEYE_SHA256:-}"

log()  { printf '[blueeye] %s\\n' "$*"; }
fail() { printf '[blueeye] ERROR: %s\\n' "$*" >&2; exit 1; }

detect_platform() {
  if [ -n "\${BLUEEYE_PLATFORM:-}" ]; then printf '%s' "$BLUEEYE_PLATFORM"; return; fi
  os=$(uname -s 2>/dev/null || echo unknown)
  arch=$(uname -m 2>/dev/null || echo unknown)
  case "$os" in
    Linux)  os=linux ;;
    Darwin) os=darwin ;;
    *)      os=$(printf '%s' "$os" | tr '[:upper:]' '[:lower:]') ;;
  esac
  case "$arch" in
    x86_64|amd64)   arch=amd64 ;;
    aarch64|arm64)  arch=arm64 ;;
    armv7l|armv7)   arch=armv7 ;;
  esac
  printf '%s-%s' "$os" "$arch"
}

# Embedded per-platform SHA-256 table (computed by the server at startup).
checksum_for() {
  case "$1" in
${checksumCase(checksums)}
  esac
}

pick_sha_tool() {
  [ -n "$SHA256" ] && return 0
  if command -v sha256sum >/dev/null 2>&1; then SHA256="sha256sum";
  elif command -v shasum >/dev/null 2>&1; then SHA256="shasum -a 256";
  else fail "no SHA-256 tool found (need sha256sum or shasum)"; fi
}

main() {
  PLATFORM=$(detect_platform)
  log "platform: $PLATFORM"
  EXPECTED=$(checksum_for "$PLATFORM")
  [ -n "$EXPECTED" ] || fail "no agent binary published for platform '$PLATFORM'"
  pick_sha_tool

  TMP=$(mktemp)
  trap 'rm -f "$TMP"' EXIT
  log "downloading agent from $SERVER_URL/enroll/agent/$PLATFORM"
  $CURL -fsSL "$SERVER_URL/enroll/agent/$PLATFORM" -o "$TMP" || fail "download failed"

  ACTUAL=$($SHA256 "$TMP" | awk '{print $1}')
  if [ "$ACTUAL" != "$EXPECTED" ]; then
    fail "checksum mismatch (expected $EXPECTED, got $ACTUAL) — refusing to install"
  fi
  log "checksum OK ($EXPECTED)"

  # Stop here in test/inspection mode — nothing has been written to the system.
  if [ -n "\${BLUEEYE_DRY_RUN:-}" ]; then log "dry-run: verified, stopping before install"; exit 0; fi

  [ "$(id -u)" = "0" ] || fail "installation needs root — re-run with sudo, e.g.  curl -sSL <url> | sudo sh"

  # Install the binary (idempotent: overwrites in place).
  mkdir -p "$INSTALL_DIR"
  install -m 0755 "$TMP" "$INSTALL_DIR/$BIN_NAME"
  log "installed $INSTALL_DIR/$BIN_NAME"

  # Exchange the code for a token (idempotent: the agent skips enrollment when a
  # token already exists). The fingerprint is pinned for this first contact.
  FP_ARG=""
  [ -n "$CERT_FINGERPRINT" ] && FP_ARG="--fingerprint $CERT_FINGERPRINT"
  BLUEEYE_SERVER_CERT_FINGERPRINT="$CERT_FINGERPRINT" \\
    "$INSTALL_DIR/$BIN_NAME" enroll --code "$ENROLL_CODE" --server "$SERVER_URL" $FP_ARG \\
    || fail "enrollment failed"

  install_service
  log "done — agent enrolled and running"
}

install_service() {
  if ! command -v systemctl >/dev/null 2>&1; then
    log "systemd not found — start the agent manually: $INSTALL_DIR/$BIN_NAME"
    return 0
  fi
  UNIT="/etc/systemd/system/$SERVICE_NAME.service"
  # Idempotent: the unit content is stable, so rewriting on re-run is a no-op.
  cat > "$UNIT" <<UNIT_EOF
[Unit]
Description=BlueEye monitoring agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
Environment=BLUEEYE_SERVER_URL=$SERVER_URL
Environment=BLUEEYE_SERVER_CERT_FINGERPRINT=$CERT_FINGERPRINT
ExecStart=$INSTALL_DIR/$BIN_NAME
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT_EOF
  systemctl daemon-reload
  systemctl enable "$SERVICE_NAME" >/dev/null 2>&1 || true
  systemctl restart "$SERVICE_NAME"
  log "service $SERVICE_NAME enabled and (re)started"
}

main "$@"
`;
}

module.exports = { renderInstallScript };
