'use strict';

// Renders the one-line installer served at GET /enroll/:code/install.sh.
//
// No pre-built binaries are involved. The script is self-contained (server URL,
// certificate fingerprint, enrollment code and the SHA-256 of the agent SOURCE
// bundle are baked in). It:
//   1. downloads the agent source from the BlueEyes server itself,
//   2. verifies SHA-256 against the embedded checksum (ABORTS on mismatch),
//   3. picks a runtime — pre-built binary by DEFAULT when the server has built one
//      (no Node.js or Docker required); then native Node + systemd; then Docker
//      (auto-detected — slim image when binary available, otherwise node:22-alpine);
//      if no runtime is available it prints clear instructions and stops — never dead-ends,
//   4. for native installs (binary or node) lays the agent out in the versioned
//      releases/<v> + `current` symlink layout (state in /var/lib, logs in
//      /var/log) so signed self-updates can swap releases atomically with rollback,
//   5. pins the release public key so SIGNED self-updates verify — from
//      BLUEEYE_RELEASE_PUBLIC_KEY if provisioned out of band, else the key
//      already pinned on the host, else (trust-on-first-use) the server's,
//   6. enrolls with the embedded one-time code (pinning the cert fingerprint).
// It is idempotent (re-running reuses the stored token) and exposes a few env
// hooks (BLUEEYE_CURL, BLUEEYE_SHA256, BLUEEYE_RUNTIME, BLUEEYE_DRY_RUN) so the
// verification path can be exercised in tests without touching the system.

const { normalizeFingerprint } = require('./fingerprint');

// Shell-quote for a double-quoted context (the inputs are server-controlled and
// already constrained — code is base64url, fingerprint is hex, serverUrl is a
// validated origin — but we quote defensively all the same).
function shDq(value) {
  return String(value == null ? '' : value).replace(/(["\\$`])/g, '\\$1');
}

function renderInstallScript({
  serverUrl,
  code,
  certFingerprint = '',
  sourceSha = '',
  serviceName = 'blueeye-agent',
  // SHA-256 of each pre-built binary (empty string = not built yet).
  binaryChecksums = {},
  // Agent version string (embedded so the binary release dir is named properly).
  agentVersion = '',
} = {}) {
  const fp = normalizeFingerprint(certFingerprint);
  const binX64   = shDq(binaryChecksums['linux-x64']   || '');
  const binArm64 = shDq(binaryChecksums['linux-arm64'] || '');
  const ver      = shDq(agentVersion || '');
  return `#!/bin/sh
# BlueEyes agent installer — generated by blueeye-server. Do not edit by hand.
#
# Everything needed is embedded below: the server URL, the certificate
# fingerprint to pin, your one-time enrollment code and the expected SHA-256 of
# the agent SOURCE bundle. The agent is downloaded from the BlueEyes server itself
# (no GitHub, no registry — works on air-gapped networks, as long as the machine
# can reach the server) and installed via the lightest runtime available:
#   1. pre-built binary  (~60 MB, no Node.js or Docker needed) — default when ready
#   2. native Node.js + systemd — fallback when Node is present
#   3. Docker (auto)    — slim image (~120 MB) if binary ready, else node:22-alpine (~500 MB)
set -eu

SERVER_URL="${shDq(serverUrl)}"
ENROLL_CODE="${shDq(code)}"
CERT_FINGERPRINT="${shDq(fp)}"
SOURCE_SHA256="${shDq(sourceSha)}"
SERVICE_NAME="${shDq(serviceName)}"
AGENT_VERSION="${ver}"
BINARY_SHA_LINUX_X64="${binX64}"
BINARY_SHA_LINUX_ARM64="${binArm64}"
INSTALL_DIR="\${BLUEEYE_INSTALL_DIR:-/opt/blueeye-agent}"
STATE_DIR="\${BLUEEYE_STATE_DIR:-/var/lib/blueeye-agent}"
LOG_DIR="\${BLUEEYE_LOG_DIR:-/var/log/blueeye-agent}"
IMAGE="\${BLUEEYE_IMAGE:-blueeye-agent}"
CONTAINER="\${BLUEEYE_CONTAINER:-blueeye-agent}"
TOKEN_VOLUME="\${BLUEEYE_TOKEN_VOLUME:-blueeye-agent-data}"

# Test/override hooks (unset in normal use).
CURL="\${BLUEEYE_CURL:-curl}"
SHA256="\${BLUEEYE_SHA256:-}"
RUNTIME="\${BLUEEYE_RUNTIME:-}"   # force binary|docker|node|none (default: auto)
UNIT_DIR="\${BLUEEYE_UNIT_DIR:-/etc/systemd/system}"

log()  { printf '[blueeye] %s\\n' "$*"; }
fail() { printf '[blueeye] ERROR: %s\\n' "$*" >&2; exit 1; }

# Resolves the release trust anchor — the Ed25519 PUBLIC key the agent verifies
# SIGNED self-updates against. The order below is a security order, not a
# convenience one:
#   1. BLUEEYE_RELEASE_PUBLIC_KEY, provisioned out of band. Always wins.
#   2. a key already pinned on this host. Re-running the installer must never
#      silently re-anchor an installed agent to a different key — that would
#      hand a server that is compromised LATER a way to replace the very anchor
#      that is supposed to detect it.
#   3. the server. Convenient (no manual provisioning) but trust-on-first-use:
#      the same host that ships the code hands out the key that authenticates
#      it, so it only protects against a later compromise. Say so out loud.
# Prints the key (PEM or base64) on stdout, or nothing when none is available.
# Callers capture stdout, so every message in here goes to stderr.
resolve_release_key() {
  if [ -n "\${BLUEEYE_RELEASE_PUBLIC_KEY:-}" ]; then
    log "release key: using the provisioned BLUEEYE_RELEASE_PUBLIC_KEY" >&2
    printf '%s' "$BLUEEYE_RELEASE_PUBLIC_KEY"
    return 0
  fi
  if [ -s "$UNIT_DIR/$SERVICE_NAME.service.d/10-release-key.conf" ]; then
    log "release key: already pinned on this host — keeping it" >&2
    return 0
  fi
  KEY_FROM_SERVER=$($CURL -fsSL "$SERVER_URL/enroll/agent-release-key" 2>/dev/null || true)
  if [ -n "$KEY_FROM_SERVER" ]; then
    log "release key: taken from the server (trust-on-first-use). To anchor it independently, re-install with BLUEEYE_RELEASE_PUBLIC_KEY set from an out-of-band copy." >&2
  fi
  printf '%s' "$KEY_FROM_SERVER"
}

# One header value from a curl -D dump, last occurrence (redirects append).
hdr_value() {
  grep -i "^$1:" "$2" 2>/dev/null | tail -n1 | sed 's/^[^:]*:[[:space:]]*//' | tr -d '\r\n'
}

# The key to VERIFY a signed release against — which is NOT the same question as
# which key to PIN. resolve_release_key() deliberately prints nothing when a key
# is already pinned, so that a re-install can never re-anchor an installed agent.
# Verification needs the actual bytes, so it reads them, and in the same security
# order: provisioned out of band, then the host's own pin, then the server.
release_key_for_verify() {
  if [ -n "\${BLUEEYE_RELEASE_PUBLIC_KEY:-}" ]; then
    printf '%s' "$BLUEEYE_RELEASE_PUBLIC_KEY"
    return 0
  fi
  PINNED_CONF="$UNIT_DIR/$SERVICE_NAME.service.d/10-release-key.conf"
  if [ -s "$PINNED_CONF" ]; then
    sed -n 's/^Environment=BLUEEYE_RELEASE_PUBLIC_KEY=//p' "$PINNED_CONF" | head -n1 | tr -d '\r\n'
    return 0
  fi
  $CURL -fsSL "$SERVER_URL/enroll/agent-release-key" 2>/dev/null || true
}

b64_decode() {
  base64 -d 2>/dev/null || openssl base64 -d -A 2>/dev/null
}

# Verifies the Ed25519 signature over the manifest. Prints one of:
#   verified    a verifier ran and the signature is good
#   failed      a verifier ran and said NO — always fatal, never a fallback
#   unverified  no verifier on this host, or no key to check against
#
# Two verifiers because the runtimes differ: a node install has node, a binary or
# docker install may have neither node nor a modern openssl. Ed25519 needs
# OpenSSL 1.1.1+, so an older one falls through rather than reporting a failure
# it is not equipped to judge.
verify_release_signature() {
  VR_MANIFEST="$1"
  VR_SIG_B64="$2"
  VR_KEY=$(release_key_for_verify)
  if [ -z "$VR_KEY" ]; then
    printf 'unverified'
    return 0
  fi

  VR_KEYFILE="$TMP/release-key"
  printf '%s' "$VR_KEY" > "$VR_KEYFILE"
  VR_SIGFILE="$TMP/release.sig.b64"
  printf '%s' "$VR_SIG_B64" > "$VR_SIGFILE"

  if command -v node >/dev/null 2>&1; then
    cat > "$TMP/verify.js" <<'BLUEEYE_VERIFY_EOF'
'use strict';
const fs = require('fs');
const crypto = require('crypto');
try {
  const [manifestFile, signatureFile, keyFile] = process.argv.slice(2);
  if (!manifestFile || !signatureFile || !keyFile) process.exit(2);
  let key = fs.readFileSync(keyFile, 'utf8').trim();
  if (key.indexOf('-----BEGIN') !== 0) key = Buffer.from(key, 'base64').toString('utf8');
  const ok = crypto.verify(
    null,
    fs.readFileSync(manifestFile),
    crypto.createPublicKey(key),
    Buffer.from(fs.readFileSync(signatureFile, 'utf8').trim(), 'base64')
  );
  process.exit(ok ? 0 : 1);
} catch (err) {
  process.exit(2);
}
BLUEEYE_VERIFY_EOF
    if node "$TMP/verify.js" "$VR_MANIFEST" "$VR_SIGFILE" "$VR_KEYFILE" >/dev/null 2>&1; then
      printf 'verified'; return 0
    fi
    # Exit 1 is a real refusal; exit 2 means the verifier could not run at all
    # (unreadable key, no Ed25519 in this Node). Only the first is a failure.
    if [ $? -eq 1 ]; then printf 'failed'; return 0; fi
  fi

  if command -v openssl >/dev/null 2>&1; then
    VR_PEM="$TMP/release-key.pem"
    if head -c 11 "$VR_KEYFILE" | grep -q -- '-----BEGIN'; then
      cp "$VR_KEYFILE" "$VR_PEM"
    else
      b64_decode < "$VR_KEYFILE" > "$VR_PEM" 2>/dev/null || true
    fi
    VR_SIGBIN="$TMP/release.sig"
    b64_decode < "$VR_SIGFILE" > "$VR_SIGBIN" 2>/dev/null || true
    if [ -s "$VR_PEM" ] && [ -s "$VR_SIGBIN" ]; then
      if openssl pkeyutl -verify -rawin -pubin -inkey "$VR_PEM" -sigfile "$VR_SIGBIN" -in "$VR_MANIFEST" >/dev/null 2>&1; then
        printf 'verified'; return 0
      fi
      # Tell "openssl says no" from "this openssl has no Ed25519": ask it.
      if openssl list -public-key-algorithms 2>/dev/null | grep -qi ed25519; then
        printf 'failed'; return 0
      fi
    fi
  fi

  printf 'unverified'
  return 0
}

# Downloads the SIGNED release and accepts it only once its signature and its
# sha256 both hold. Sets TARBALL on success.
#
# Returns 0 = use it, 1 = the server publishes no signed release (fall back to
# the source bundle). A release that IS published and fails to verify does not
# return 1 — it aborts. Falling back there would let anyone who can break the
# signature downgrade the install to the unsigned path just by breaking it.
fetch_signed_release() {
  SR_HDR="$TMP/release.hdr"
  SR_TGZ="$TMP/agent-release.tgz"
  if ! $CURL -fsSL -D "$SR_HDR" "$SERVER_URL/enroll/agent-release.tgz" -o "$SR_TGZ" 2>/dev/null; then
    return 1
  fi

  SR_MANIFEST_B64=$(hdr_value 'X-Release-Manifest' "$SR_HDR")
  SR_SIG=$(hdr_value 'X-Release-Signature' "$SR_HDR")
  SR_VERSION=$(hdr_value 'X-Release-Version' "$SR_HDR")
  if [ -z "$SR_MANIFEST_B64" ] || [ -z "$SR_SIG" ]; then
    log "signed release: the server served one without a manifest or signature — falling back to the source bundle"
    return 1
  fi

  SR_MANIFEST="$TMP/release-manifest.bin"
  printf '%s' "$SR_MANIFEST_B64" | b64_decode > "$SR_MANIFEST" 2>/dev/null || true
  [ -s "$SR_MANIFEST" ] || fail "the signed release manifest could not be decoded — refusing to install"

  # The sha256 the PUBLISHER put its name to. Read by pattern from the canonical
  # manifest (keys sorted, no whitespace), and required to be exactly 64 hex, so
  # a truncated or decorated value fails rather than matching something shorter.
  SR_WANT=$(grep -o '"sha256":"[0-9a-f]\\{64\\}"' "$SR_MANIFEST" | head -n1 | sed 's/.*:"//; s/"$//')
  [ -n "$SR_WANT" ] || fail "the signed release manifest carries no usable sha256 — refusing to install"

  pick_sha_tool
  SR_ACTUAL=$($SHA256 "$SR_TGZ" | awk '{print $1}')
  if [ "$SR_ACTUAL" != "$SR_WANT" ]; then
    fail "the signed release that arrived does not match its own signed manifest (manifest says $SR_WANT, got $SR_ACTUAL) — something between this host and the server altered or cached it. Refusing to install."
  fi

  SR_VERDICT=$(verify_release_signature "$SR_MANIFEST" "$SR_SIG")
  case "$SR_VERDICT" in
    verified)
      log "signed release v\${SR_VERSION:-?}: signature verified, sha256 matches its manifest"
      ;;
    failed)
      fail "the signed release v\${SR_VERSION:-?} did NOT pass signature verification against the key this host trusts — refusing to install. If the server's signing key was rotated, re-pin this host (Settings -> Updates shows the command)."
      ;;
    *)
      # No verifier here. The artefact is still strictly better than the source
      # bundle: it is published once and never repackaged, so its checksum does
      # not move under the installer, and the sha256 just checked came out of the
      # signed manifest rather than from a second request that a cache can answer
      # separately. Say plainly what was not done.
      if [ -n "\${BLUEEYE_REQUIRE_SIGNED_INSTALL:-}" ]; then
        fail "BLUEEYE_REQUIRE_SIGNED_INSTALL is set, but this host has no way to verify an Ed25519 signature (needs node, or OpenSSL 1.1.1+) — refusing to install."
      fi
      log "signed release v\${SR_VERSION:-?}: sha256 matches its manifest, but the SIGNATURE could not be checked here (no node, no Ed25519-capable openssl). Set BLUEEYE_REQUIRE_SIGNED_INSTALL=1 to refuse instead."
      ;;
  esac

  TARBALL="$SR_TGZ"
  [ -n "$SR_VERSION" ] && AGENT_VERSION="$SR_VERSION"
  return 0
}

pick_sha_tool() {
  [ -n "$SHA256" ] && return 0
  if command -v sha256sum >/dev/null 2>&1; then SHA256="sha256sum";
  elif command -v shasum >/dev/null 2>&1; then SHA256="shasum -a 256";
  else fail "no SHA-256 tool found (need sha256sum or shasum)"; fi
}

# Returns the arch slug that matches this host, or empty on unsupported arch.
# The pre-built binaries are Linux-only, so a non-Linux kernel (e.g. macOS, whose
# uname -m is also x86_64/arm64) must NOT match one — it would download a Linux
# executable and fail to run. macOS/other kernels fall through to node/docker.
pick_binary_arch() {
  [ "$(uname -s)" = "Linux" ] || { printf ''; return 0; }
  case "$(uname -m)" in
    x86_64|amd64)  printf '%s' "linux-x64"  ;;
    aarch64|arm64) printf '%s' "linux-arm64" ;;
    *)             printf ''                  ;;
  esac
}

# Returns the embedded binary SHA-256 for this host's arch, or empty.
pick_binary_sha() {
  [ "$(uname -s)" = "Linux" ] || { printf ''; return 0; }
  case "$(uname -m)" in
    x86_64|amd64)  printf '%s' "$BINARY_SHA_LINUX_X64"  ;;
    aarch64|arm64) printf '%s' "$BINARY_SHA_LINUX_ARM64" ;;
    *)             printf ''                              ;;
  esac
}

# Point the \`current\` symlink at $1 (a release dir). On Linux we stage the new
# link then rename it over the old one — an atomic replace (mv -T needs GNU mv).
# BSD/macOS mv has no -T (and would move INTO the target dir), so there we replace
# the symlink directly; still effectively instantaneous for a symlink swap.
point_current() {
  DEST_LINK="$1"
  if [ "$(uname -s)" = "Darwin" ]; then
    rm -f "$CURRENT" && ln -sfn "$DEST_LINK" "$CURRENT" || fail "could not point current -> $DEST_LINK"
  else
    ln -sfn "$DEST_LINK" "$CURRENT.next" && mv -T "$CURRENT.next" "$CURRENT" || fail "could not point current -> $DEST_LINK"
  fi
}

main() {
  TMP=$(mktemp -d)
  trap 'rm -rf "$TMP"' EXIT

  # THE SIGNED RELEASE FIRST. It is a fixed artefact: published once, never
  # repackaged, and carrying its own signed manifest — so its checksum does not
  # move under the installer, and the sha256 it is checked against travels WITH
  # the bytes instead of coming from a second request a cache can answer on its
  # own. The source bundle below has neither property: it is rebuilt whenever the
  # server starts, and its checksum is fetched separately.
  TARBALL=""
  if fetch_signed_release; then
    log "installing the signed release (source bundle not needed)"
  else
    log "no signed release published on this server — using the source bundle"
    [ -n "$SOURCE_SHA256" ] || fail "the BlueEyes server has no agent source published either — set AGENT_SOURCE_DIR on the server (see docs/enrollment.md), or publish a signed release, then retry"
    fetch_source_bundle
  fi

  # Stop here in test/inspection mode — nothing has been written to the system.
  if [ -n "\${BLUEEYE_DRY_RUN:-}" ]; then log "dry-run: verified, stopping before install"; exit 0; fi

  install_from_tarball
}

# The legacy path: an unsigned tarball, checked against a checksum this script
# had baked into it when the server generated it.
fetch_source_bundle() {
  TARBALL="$TMP/agent-source.tgz"

  log "downloading agent source from $SERVER_URL/enroll/agent-source.tgz"
  # ?sha= is what keeps the tarball and the checksum embedded in this script in
  # step. They arrive in two separate requests, so they can only disagree when
  # something changed or was cached in between: the query makes the URL unique per
  # server build (nothing in the path can answer it with an older tarball), and a
  # server that has repackaged since answers 409 rather than handing over bytes
  # this script would then call corrupt.
  if ! $CURL -fsSL "$SERVER_URL/enroll/agent-source.tgz?sha=$SOURCE_SHA256" -o "$TARBALL"; then
    LIVE=$($CURL -fsSL "$SERVER_URL/enroll/agent-source.sha256" 2>/dev/null | tr -d '\r' | head -n1 || true)
    if [ -n "$LIVE" ] && [ "$LIVE" != "$SOURCE_SHA256" ]; then
      fail "this install script is out of date: it expects agent source $SOURCE_SHA256, but the server now serves $LIVE — re-run the one-liner from the dashboard to get a current script"
    fi
    fail "download failed"
  fi

  pick_sha_tool
  ACTUAL=$($SHA256 "$TARBALL" | awk '{print $1}')
  if [ "$ACTUAL" != "$SOURCE_SHA256" ]; then
    # Name the side that is stale. "checksum mismatch" on its own sends operators
    # hunting for a corrupted download, which is almost never what happened.
    LIVE=$($CURL -fsSL "$SERVER_URL/enroll/agent-source.sha256" 2>/dev/null | tr -d '\r' | head -n1 || true)
    if [ "$LIVE" = "$ACTUAL" ]; then
      fail "this install script is out of date: it expects agent source $SOURCE_SHA256, but the server now serves $LIVE — which is what was just downloaded. Re-run the one-liner from the dashboard."
    fi
    if [ "$LIVE" = "$SOURCE_SHA256" ]; then
      fail "the agent source that arrived is not what the server says it serves (expected $SOURCE_SHA256, got $ACTUAL) — something between this host and the server returned a stale or altered copy. Check any proxy or cache in the path, then retry."
    fi
    fail "checksum mismatch (expected $SOURCE_SHA256, got $ACTUAL) — refusing to install. The server currently serves: \${LIVE:-unknown (the server could not be asked)}"
  fi
  log "checksum OK ($SOURCE_SHA256)"
}

install_from_tarball() {
  # Pick a runtime. Priority order (unless BLUEEYE_RUNTIME overrides):
  #   binary  — pre-built self-contained executable; no Node.js or Docker needed
  #   node    — native Node.js + systemd
  #   docker  — containerised; auto when Docker is found and no better runtime is available
  #   none    — nothing available; print instructions and exit
  if [ -z "$RUNTIME" ]; then
    BINARY_SHA=$(pick_binary_sha)
    if [ -n "$BINARY_SHA" ]; then
      RUNTIME=binary
    elif command -v node >/dev/null 2>&1; then
      RUNTIME=node
    elif command -v docker >/dev/null 2>&1; then
      RUNTIME=docker
    else
      RUNTIME=none
    fi
  fi
  if [ "$RUNTIME" = "docker" ] && ! command -v docker >/dev/null 2>&1; then
    fail "Docker runtime selected but Docker is not installed on this host.
  - install Docker:  https://docs.docker.com/engine/install/
  - or install Node.js for a native install:  https://nodejs.org/"
  fi
  if [ "$RUNTIME" = "none" ]; then
    fail "Node.js was not found on this host — no compatible runtime available.
Install one of the following and re-run:
  - pre-built binary:  retry once the server has finished building (check agent-binary-status)
  - Node.js 18+:       https://nodejs.org/
  - Docker:            https://docs.docker.com/engine/install/
then:  curl -sSL $SERVER_URL/enroll/$ENROLL_CODE/install.sh | sh"
  fi
  log "runtime: $RUNTIME"

  [ "$(id -u)" = "0" ] || fail "installation needs root — re-run with sudo, e.g.  curl -sSL <url> | sudo sh"

  if   [ "$RUNTIME" = "binary" ]; then install_binary "$TARBALL"
  elif [ "$RUNTIME" = "docker" ]; then install_docker "$TARBALL"
  else                                  install_node   "$TARBALL"
  fi
  run_doctor
  log "to remove the agent later: curl -sSL $SERVER_URL/enroll/uninstall.sh | sudo sh"
}

# Connection self-test after install: run the agent's built-in \`doctor\` so the
# install ends with a CONNECTED / NOT-CONNECTED verdict + fix suggestions instead
# of a silent success. Informational only — never fails the install (|| true); an
# older agent source without 'doctor' just prints usage.
run_doctor() {
  log "running connection self-test (blueeye-agent doctor) ..."
  DOC_ENV="BLUEEYE_TOKEN_PATH=$TOKEN_PATH BLUEEYE_AGENT_CONFIG=$CONFIG_PATH BLUEEYE_SERVER_URL=$SERVER_URL BLUEEYE_SERVER_CERT_FINGERPRINT=$CERT_FINGERPRINT"
  case "$RUNTIME" in
    node)   env $DOC_ENV node "$CURRENT/src/index.js" doctor || true ;;
    binary) env $DOC_ENV "$CURRENT/blueeye-agent" doctor || true ;;
    docker) docker exec "$CONTAINER" node src/index.js doctor || true ;;
  esac
}

install_binary() {
  TARBALL_PATH="$1"
  BINARY_ARCH=$(pick_binary_arch)
  BINARY_SHA=$(pick_binary_sha)
  [ -n "$BINARY_ARCH" ] || fail "unsupported architecture '$(uname -m)' for binary install"
  [ -n "$BINARY_SHA"  ] || fail "no binary SHA for this arch — re-run install.sh (the server may still be building)"

  RELEASES="$INSTALL_DIR/releases"
  CURRENT="$INSTALL_DIR/current"
  TOKEN_PATH="$STATE_DIR/token"
  CONFIG_PATH="$STATE_DIR/config.json"
  mkdir -p "$RELEASES" "$STATE_DIR" "$LOG_DIR"

  # Stage binary, verify, move into versioned release dir.
  STAGE="$RELEASES/.stage.$$"
  rm -rf "$STAGE"; mkdir -p "$STAGE"

  log "downloading pre-built agent binary ($BINARY_ARCH) ..."
  $CURL -fsSL "$SERVER_URL/enroll/agent-binary/$BINARY_ARCH" -o "$STAGE/blueeye-agent" \\
    || fail "binary download failed"
  chmod +x "$STAGE/blueeye-agent"

  ACTUAL_BIN=$($SHA256 "$STAGE/blueeye-agent" | awk '{print $1}')
  [ "$ACTUAL_BIN" = "$BINARY_SHA" ] \\
    || fail "binary checksum mismatch (expected $BINARY_SHA, got $ACTUAL_BIN)"
  log "binary checksum OK"

  DEST="$RELEASES/\${AGENT_VERSION:-$(date +%Y%m%d%H%M%S)}"
  rm -rf "$DEST"; mv "$STAGE" "$DEST"

  # Resolve the release trust anchor (same as the node install path).
  RELEASE_KEY=$(resolve_release_key)

  # Enroll once (idempotent: skipped when a token already exists).
  FP_ARG=""
  [ -n "$CERT_FINGERPRINT" ] && FP_ARG="--fingerprint $CERT_FINGERPRINT"
  # shellcheck disable=SC2086
  BLUEEYE_TOKEN_PATH="$TOKEN_PATH" BLUEEYE_AGENT_CONFIG="$CONFIG_PATH" \\
  BLUEEYE_SERVER_CERT_FINGERPRINT="$CERT_FINGERPRINT" \\
    "$DEST/blueeye-agent" enroll --code "$ENROLL_CODE" --server "$SERVER_URL" $FP_ARG \\
    || fail "enrollment failed"

  point_current "$DEST"

  install_service "$CURRENT/blueeye-agent" binary
  log "done — agent v\${AGENT_VERSION:-?} enrolled and running (binary)"
}

install_docker() {
  TARBALL_PATH="$1"
  mkdir -p "$INSTALL_DIR"
  log "extracting agent source to $INSTALL_DIR"
  tar -xzf "$TARBALL_PATH" -C "$INSTALL_DIR" || fail "could not extract the agent source"

  # If the server has a pre-built binary and Dockerfile.slim is present, use the
  # slim image (debian:12-slim + binary ≈ 120 MB) instead of node:22-alpine (≈ 500 MB).
  BINARY_ARCH=$(pick_binary_arch)
  BINARY_SHA=$(pick_binary_sha)
  SLIM_DOCKERFILE="$INSTALL_DIR/Dockerfile.slim"
  USE_SLIM=0
  if [ -n "$BINARY_ARCH" ] && [ -n "$BINARY_SHA" ] && [ -f "$SLIM_DOCKERFILE" ]; then
    log "downloading pre-built binary for slim Docker image ($BINARY_ARCH) ..."
    if $CURL -fsSL "$SERVER_URL/enroll/agent-binary/$BINARY_ARCH" -o "$INSTALL_DIR/blueeye-agent-linux" 2>/dev/null; then
      ACTUAL_BIN=$($SHA256 "$INSTALL_DIR/blueeye-agent-linux" | awk '{print $1}')
      if [ "$ACTUAL_BIN" = "$BINARY_SHA" ]; then
        USE_SLIM=1
        log "binary checksum OK — using slim image (saves ~380 MB)"
      else
        log "binary checksum mismatch — falling back to node:22-alpine image"
        rm -f "$INSTALL_DIR/blueeye-agent-linux"
      fi
    else
      log "binary download failed — falling back to node:22-alpine image"
    fi
  fi

  if [ "$USE_SLIM" = "1" ]; then
    log "building slim image $IMAGE ..."
    docker build -t "$IMAGE" -f "$SLIM_DOCKERFILE" "$INSTALL_DIR" >/dev/null || fail "docker build (slim) failed"
  else
    log "building image $IMAGE (this can take a minute) ..."
    docker build -t "$IMAGE" "$INSTALL_DIR" >/dev/null || fail "docker build failed"
  fi

  docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
  docker volume create "$TOKEN_VOLUME" >/dev/null
  FP_ENV=""
  [ -n "$CERT_FINGERPRINT" ] && FP_ENV="-e BLUEEYE_SERVER_CERT_FINGERPRINT=$CERT_FINGERPRINT"
  # Host networking so the agent sees the host's real interfaces. The agent
  # enrolls itself on first start from BLUEEYE_ENROLLMENT_CODE; the token lives on
  # the named volume, so re-runs are idempotent (the code is then ignored).
  # shellcheck disable=SC2086
  docker run -d --name "$CONTAINER" --restart unless-stopped --network host \\
    -e "BLUEEYE_SERVER_URL=$SERVER_URL" \\
    -e "BLUEEYE_ENROLLMENT_CODE=$ENROLL_CODE" \\
    -e "BLUEEYE_TOKEN_PATH=/data/token" \\
    -e "BLUEEYE_RUNTIME=docker" \\
    $FP_ENV \\
    -v "$TOKEN_VOLUME:/data" \\
    "$IMAGE" >/dev/null || fail "docker run failed"
  log "done — agent running as docker container '$CONTAINER'  (docker logs -f $CONTAINER)"
}

install_node() {
  TARBALL_PATH="$1"
  command -v node >/dev/null 2>&1 || fail "Node not found"
  command -v npm  >/dev/null 2>&1 || fail "npm is required to install the agent's dependencies (or use Docker: BLUEEYE_RUNTIME=docker)"
  NODE_BIN=$(command -v node)

  RELEASES="$INSTALL_DIR/releases"
  CURRENT="$INSTALL_DIR/current"
  TOKEN_PATH="$STATE_DIR/token"
  CONFIG_PATH="$STATE_DIR/config.json"
  mkdir -p "$RELEASES" "$STATE_DIR" "$LOG_DIR"

  # Stage the verified bundle INSIDE releases/ (same filesystem, so the final
  # rename is atomic), read its version, then place it as releases/<version>.
  STAGE="$RELEASES/.stage.$$"
  rm -rf "$STAGE"; mkdir -p "$STAGE"
  tar -xzf "$TARBALL_PATH" -C "$STAGE" || { rm -rf "$STAGE"; fail "could not extract the agent source"; }
  VERSION=$(node -p "require('$STAGE/package.json').version" 2>/dev/null || true)
  [ -n "$VERSION" ] || VERSION="source-$(date +%Y%m%d%H%M%S)"
  DEST="$RELEASES/$VERSION"
  rm -rf "$DEST"; mv "$STAGE" "$DEST"

  log "installing dependencies (npm) for v$VERSION ..."
  ( cd "$DEST" && { npm ci --omit=dev >/dev/null 2>&1 || npm install --omit=dev >/dev/null 2>&1; } ) || fail "dependency install failed"

  # Atomic blue/green: point \`current\` at the new release (rename over a symlink
  # is atomic on POSIX), so a later signed update swaps releases the same way.
  point_current "$DEST"

  # Resolve the release trust anchor (Ed25519 public key) so SIGNED self-updates
  # verify. Not secret; optional (no key anywhere -> empty -> unsigned-only).
  RELEASE_KEY=$(resolve_release_key)

  # Enroll once (idempotent: skipped when a token already exists), writing the
  # token to the SHARED state dir so a release swap never loses it.
  FP_ARG=""
  [ -n "$CERT_FINGERPRINT" ] && FP_ARG="--fingerprint $CERT_FINGERPRINT"
  # shellcheck disable=SC2086
  BLUEEYE_TOKEN_PATH="$TOKEN_PATH" BLUEEYE_AGENT_CONFIG="$CONFIG_PATH" BLUEEYE_SERVER_CERT_FINGERPRINT="$CERT_FINGERPRINT" \\
    node "$CURRENT/src/index.js" enroll --code "$ENROLL_CODE" --server "$SERVER_URL" $FP_ARG \\
    || fail "enrollment failed"

  install_service "$NODE_BIN $CURRENT/src/index.js" systemd
  log "done — agent v$VERSION enrolled and running (node + systemd)"
}

# install_launchd EXEC_START RUNTIME_TAG
# macOS service install: writes a LaunchDaemon plist that runs the agent from the
# \`current\` symlink and reloads it. Env mirrors the systemd unit so token/config/
# logs live outside the swappable release dir. Label: com.blueeye.agent.
install_launchd() {
  EXEC_START="$1"
  RUNTIME_TAG="\${2:-launchd}"
  LABEL="com.blueeye.agent"
  PLIST="/Library/LaunchDaemons/$LABEL.plist"

  {
    printf '%s\\n' '<?xml version="1.0" encoding="UTF-8"?>'
    printf '%s\\n' '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
    printf '%s\\n' '<plist version="1.0"><dict>'
    printf '  <key>Label</key><string>%s</string>\\n' "$LABEL"
    printf '%s\\n' '  <key>ProgramArguments</key><array>'
    # EXEC_START is a space-joined command (e.g. "/usr/local/bin/node /opt/.../src/index.js");
    # the install paths we control have no spaces, so word-splitting is safe here.
    # shellcheck disable=SC2086
    for arg in $EXEC_START; do printf '    <string>%s</string>\\n' "$arg"; done
    printf '%s\\n' '  </array>'
    printf '  <key>WorkingDirectory</key><string>%s</string>\\n' "$CURRENT"
    printf '%s\\n' '  <key>EnvironmentVariables</key><dict>'
    printf '    <key>BLUEEYE_SERVER_URL</key><string>%s</string>\\n' "$SERVER_URL"
    printf '    <key>BLUEEYE_SERVER_CERT_FINGERPRINT</key><string>%s</string>\\n' "$CERT_FINGERPRINT"
    printf '    <key>BLUEEYE_TOKEN_PATH</key><string>%s</string>\\n' "$TOKEN_PATH"
    printf '    <key>BLUEEYE_AGENT_CONFIG</key><string>%s</string>\\n' "$CONFIG_PATH"
    printf '    <key>BLUEEYE_ACTION_LOG</key><string>%s</string>\\n' "$LOG_DIR/actions.log"
    printf '    <key>BLUEEYE_RELEASES_DIR</key><string>%s</string>\\n' "$RELEASES"
    printf '    <key>BLUEEYE_CURRENT_LINK</key><string>%s</string>\\n' "$CURRENT"
    printf '    <key>BLUEEYE_RUNTIME</key><string>%s</string>\\n' "$RUNTIME_TAG"
    printf '    <key>BLUEEYE_SERVICE_NAME</key><string>%s</string>\\n' "$SERVICE_NAME"
    printf '%s\\n' '  </dict>'
    printf '%s\\n' '  <key>RunAtLoad</key><true/>'
    printf '%s\\n' '  <key>KeepAlive</key><true/>'
    printf '  <key>StandardOutPath</key><string>%s</string>\\n' "$LOG_DIR/agent.log"
    printf '  <key>StandardErrorPath</key><string>%s</string>\\n' "$LOG_DIR/agent.err.log"
    printf '%s\\n' '</dict></plist>'
  } > "$PLIST" || fail "could not write $PLIST"

  # Reload: bootout the old daemon (ignored if not loaded) then bootstrap the new
  # one. Fall back to legacy load/unload on older macOS without bootstrap.
  if launchctl bootstrap system "$PLIST" 2>/dev/null; then
    launchctl kickstart -k "system/$LABEL" 2>/dev/null || true
  else
    launchctl unload "$PLIST" 2>/dev/null || true
    launchctl load -w "$PLIST" || fail "launchctl load failed"
  fi
  log "launchd daemon $LABEL loaded (starts at boot; manage with: sudo launchctl print system/$LABEL)"
}

# install_service EXEC_START RUNTIME_TAG
# Installs (or reinstalls) the systemd unit that runs the agent.
# EXEC_START — the full ExecStart value (e.g. "/opt/.../blueeye-agent" or "node .../src/index.js")
# RUNTIME_TAG — value for BLUEEYE_RUNTIME env var in the unit
install_service() {
  EXEC_START="$1"
  RUNTIME_TAG="\${2:-systemd}"

  # macOS: run under launchd as a LaunchDaemon (starts at boot, KeepAlive restarts
  # on exit) — the platform-native equivalent of the systemd unit. Label matches
  # the server's connection-diagnosis hints (system/com.blueeye.agent).
  if [ "$(uname -s)" = "Darwin" ]; then
    install_launchd "$EXEC_START" "$RUNTIME_TAG"
    return $?
  fi

  if ! command -v systemctl >/dev/null 2>&1; then
    log "systemd not found — start the agent manually:"
    log "  $EXEC_START"
    return 0
  fi
  UNIT="$UNIT_DIR/$SERVICE_NAME.service"
  # Runs from the \`current\` symlink so a signed update can swap the release dir
  # underneath atomically. Token/config/log live OUTSIDE the swappable release dir
  # so updates never touch them.
  cat > "$UNIT" <<UNIT_EOF
[Unit]
Description=BlueEyes monitoring agent
Documentation=https://github.com/gudlever-lgtm/blueeye-agent
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=120
StartLimitBurst=5

[Service]
Type=simple
WorkingDirectory=$CURRENT
ExecStart=$EXEC_START
Restart=on-failure
RestartSec=5
Environment=BLUEEYE_SERVER_URL=$SERVER_URL
Environment=BLUEEYE_SERVER_CERT_FINGERPRINT=$CERT_FINGERPRINT
Environment=BLUEEYE_TOKEN_PATH=$TOKEN_PATH
Environment=BLUEEYE_AGENT_CONFIG=$CONFIG_PATH
Environment=BLUEEYE_ACTION_LOG=$LOG_DIR/actions.log
Environment=BLUEEYE_RELEASES_DIR=$RELEASES
Environment=BLUEEYE_CURRENT_LINK=$CURRENT
Environment=BLUEEYE_RUNTIME=$RUNTIME_TAG
Environment=BLUEEYE_SERVICE_NAME=$SERVICE_NAME

# Sandboxing — bounds what the (root) agent process can reach, while staying
# compatible with self-update (tar + npm, then systemctl restart), self-delete
# (uninstall.sh) and install-tool (host package manager). Kept in sync with
# blueeye-agent deploy/blueeye-agent.service, which documents why
# ProtectSystem=, ProcSubset=, CapabilityBoundingSet= and SystemCallFilter= are
# deliberately absent.
NoNewPrivileges=yes
PrivateTmp=yes
ProtectHome=read-only
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectControlGroups=yes
RestrictNamespaces=yes
RestrictRealtime=yes
LockPersonality=yes
# AF_NETLINK: \`ss\` (connection table) and \`ethtool\` (NIC inventory). AF_UNIX:
# the D-Bus call behind systemctl.
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
UMask=0077
LimitCORE=0

[Install]
WantedBy=multi-user.target
UNIT_EOF

  # Release trust anchor as a drop-in (base64 keeps the multi-line PEM on a single
  # Environment= line; the agent decodes base64-of-PEM). RELEASE_KEY comes from
  # resolve_release_key, which returns EMPTY when a key is already pinned here —
  # so a re-install never re-anchors an installed agent to a different key.
  if [ -z "$RELEASE_KEY" ] && [ -s "$UNIT.d/10-release-key.conf" ]; then
    log "signed self-updates: keeping the release key already pinned on this host"
  elif [ -n "$RELEASE_KEY" ] && command -v base64 >/dev/null 2>&1; then
    mkdir -p "$UNIT.d"
    KEY_B64=$(printf '%s' "$RELEASE_KEY" | base64 | tr -d '\\n')
    {
      echo "[Service]"
      printf 'Environment=BLUEEYE_RELEASE_PUBLIC_KEY=%s\\n' "$KEY_B64"
    } > "$UNIT.d/10-release-key.conf"
    log "signed self-updates enabled (release key pinned)"
  elif [ -n "$RELEASE_KEY" ]; then
    log "note: 'base64' missing — set BLUEEYE_RELEASE_PUBLIC_KEY manually for signed self-updates"
  else
    log "note: no release key available — signed self-updates need BLUEEYE_RELEASE_PUBLIC_KEY set manually"
  fi

  systemctl daemon-reload
  systemctl enable "$SERVICE_NAME" >/dev/null 2>&1 || true
  systemctl restart "$SERVICE_NAME"
  log "service $SERVICE_NAME enabled and (re)started"
}

main "$@"
`;
}

module.exports = { renderInstallScript };
