'use strict';

// The RE-PIN script, served at GET /enroll/repin.sh.
//
// An agent installed by install.sh pins the server's Ed25519 release public key
// (the drop-in `10-release-key.conf`) and then refuses any update that is not
// signed by it — including an UNSIGNED one, which is the fail-closed answer to a
// signature downgrade. That is the right default, and it also means a fleet can
// get stuck: if the server's signing key is replaced (rotated, regenerated after
// a delete, or lost because the private key can no longer be decrypted), every
// one-click update on a pinned agent fails with
//
//   refusing unsigned update: a release public key is pinned …
//   release signature did not verify — refusing to install
//
// and the only way out was to re-run the installer — which needs an enrollment
// code and would onboard a SECOND agent for the same host. This script is the
// way out: it re-anchors an already-installed agent to the key this server
// serves NOW, and does nothing else. No enrollment code, no identity change, no
// code change — so it can never produce a duplicate agent.
//
// Trust: this is deliberately trust-on-first-use again, exactly as the install
// was — the host takes the key from the same server that ships its code. It is
// run by an administrator on the host, and it prints the key fingerprint so it
// can be compared with Settings → Agent key in the dashboard before restarting.

function shDq(value) {
  return String(value == null ? '' : value).replace(/(["\\$`])/g, '\\$1');
}

function renderRepinScript({ serverUrl, serviceName = 'blueeye-agent' } = {}) {
  return `#!/bin/sh
# BlueEyes agent re-pin — generated by blueeye-server. Do not edit by hand.
#
# Re-anchors THIS host's installed agent to the release signing key the BlueEyes
# server serves right now, so signed self-updates work again after the server's
# key changed. It does not enroll, does not touch the agent's token or identity,
# and does not change the agent's code.
#
#   curl -fsSL ${serverUrl}/enroll/repin.sh | sudo sh
#
set -eu

SERVER_URL="${shDq(serverUrl)}"
SERVICE_NAME="${shDq(serviceName)}"
UNIT_DIR="\${BLUEEYE_UNIT_DIR:-/etc/systemd/system}"
CURL="\${BLUEEYE_CURL:-curl}"

log()  { printf '[blueeye] %s\\n' "$*"; }
fail() { printf '[blueeye] ERROR: %s\\n' "$*" >&2; exit 1; }

[ "$(id -u)" = "0" ] || fail "run this as root (sudo): it edits the systemd unit."
command -v systemctl >/dev/null 2>&1 || fail "no systemd on this host — the release key is pinned per install; set BLUEEYE_RELEASE_PUBLIC_KEY wherever this agent's environment is defined."
command -v base64 >/dev/null 2>&1 || fail "'base64' is required (the PEM is stored base64-encoded on one Environment= line)."

UNIT="$UNIT_DIR/$SERVICE_NAME.service"
[ -f "$UNIT" ] || fail "no installed agent found at $UNIT — nothing to re-pin."

# The key as this server serves it TODAY. An empty/404 answer means the server
# has no signing key, so re-pinning would only swap one broken state for
# another: stop, and say what to do first.
KEY=$($CURL -fsSL "$SERVER_URL/enroll/agent-release-key" 2>/dev/null || true)
case "$KEY" in
  *"BEGIN PUBLIC KEY"*) : ;;
  *) fail "this server publishes no release signing key. Generate one in the dashboard (Settings -> Agent key), then run this again." ;;
esac

if command -v openssl >/dev/null 2>&1; then
  FP=$(printf '%s' "$KEY" | openssl dgst -sha256 | sed 's/^.*= //')
  log "server release key fingerprint (sha256 of the PEM): $FP"
  log "compare it with Settings -> Agent key in the dashboard before trusting this host to it."
fi

mkdir -p "$UNIT.d"
KEY_B64=$(printf '%s' "$KEY" | base64 | tr -d '\\n')
{
  echo "[Service]"
  printf 'Environment=BLUEEYE_RELEASE_PUBLIC_KEY=%s\\n' "$KEY_B64"
} > "$UNIT.d/10-release-key.conf"
chmod 0644 "$UNIT.d/10-release-key.conf"
log "release key re-pinned in $UNIT.d/10-release-key.conf"

systemctl daemon-reload
systemctl restart "$SERVICE_NAME"
log "restarted $SERVICE_NAME — signed updates from this server are accepted again."
`;
}

module.exports = { renderRepinScript };
