#!/usr/bin/env bash
#
# End-to-end smoke test for the BlueEye stack.
#
#   1. Registers a test agent
#   2. Pushes one job of each built-in type (ping, dns, http)
#   3. Polls until the agent reports results
#   4. Checks a 404 response for an unknown agent
#   5. Checks a 500 response for a malformed job
#
# Requires the stack to be running (docker compose up) and certificates
# generated by scripts/gen_certs.sh.

set -uo pipefail

SERVER="${SERVER:-https://localhost:8443}"
CERT_DIR="${CERT_DIR:-$(cd "$(dirname "$0")/.." && pwd)/certs}"
AGENT_ID="${AGENT_ID:-agent-001}"
POLL_TIMEOUT="${POLL_TIMEOUT:-150}"

CURL_OPTS=(
  --cert  "$CERT_DIR/${AGENT_ID}.crt"
  --key   "$CERT_DIR/${AGENT_ID}.key"
  --cacert "$CERT_DIR/ca.crt"
)

pass=0
fail=0
ok()  { echo "  PASS: $1"; pass=$((pass + 1)); }
no()  { echo "  FAIL: $1"; fail=$((fail + 1)); }

# request METHOD PATH [JSON-DATA] -> sets global CODE and BODY
request() {
  local method="$1" path="$2" data="${3:-}" resp
  if [[ -n "$data" ]]; then
    resp=$(curl -sS "${CURL_OPTS[@]}" -X "$method" \
           -H "Content-Type: application/json" -d "$data" \
           -w $'\n%{http_code}' "$SERVER$path")
  else
    resp=$(curl -sS "${CURL_OPTS[@]}" -X "$method" \
           -w $'\n%{http_code}' "$SERVER$path")
  fi
  CODE="${resp##*$'\n'}"
  BODY="${resp%$'\n'*}"
}

echo "BlueEye smoke test -> $SERVER"
echo

echo "[1] Register test agent '$AGENT_ID'"
request POST /agents/register \
  '{"location":"Smoke Lab","connection":"test-uplink"}'
if [[ "$CODE" == "201" ]]; then
  ok "agent registered ($CODE)"
else
  no "expected 201, got $CODE: $BODY"
fi

echo
echo "[2] Push one job of each built-in type"
for spec in 'ping|8.8.8.8' 'dns|example.com' 'http|https://example.com'; do
  type="${spec%%|*}"
  target="${spec##*|}"
  request POST /jobs \
    "{\"agent_id\":\"$AGENT_ID\",\"type\":\"$type\",\"target\":\"$target\"}"
  if [[ "$CODE" == "201" ]]; then
    ok "queued $type job ($CODE)"
  else
    no "queueing $type expected 201, got $CODE: $BODY"
  fi
done

echo
echo "[3] Poll for results (timeout ${POLL_TIMEOUT}s)"
deadline=$(( $(date +%s) + POLL_TIMEOUT ))
count=0
while (( $(date +%s) < deadline )); do
  request GET "/agents/$AGENT_ID/results"
  count=$(grep -o '"job_id"' <<<"$BODY" | wc -l | tr -d ' ')
  if (( count >= 3 )); then
    break
  fi
  sleep 5
done
if (( count >= 3 )); then
  ok "agent reported $count result(s)"
else
  no "expected >=3 results, saw $count (is the agent container running?)"
fi

echo
echo "[4] Unknown agent must return 404"
request GET "/agents/no-such-agent-xyz/jobs"
if [[ "$CODE" == "404" ]]; then
  ok "unknown agent -> 404"
else
  no "expected 404, got $CODE: $BODY"
fi

echo
echo "[5] Malformed job must return 500"
request POST /jobs 'this-is-not-json'
if [[ "$CODE" == "500" ]]; then
  ok "malformed job -> 500"
else
  no "expected 500, got $CODE: $BODY"
fi

echo
echo "------------------------------------"
echo "Results: $pass passed, $fail failed"
(( fail == 0 )) && { echo "SMOKE TEST PASSED"; exit 0; }
echo "SMOKE TEST FAILED"
exit 1
