'use strict';

// UI string catalogue (PT = "page text") for dashboard components that are
// localised. Today only the Trafiktyper card on the Trafik (overview) page uses
// it; the rest of the dashboard is Danish-only. Keep every language in sync:
// each locale must define the same set of keys.
//
// Single source of truth — required server-side and also exposed to the browser
// as a `window.PT` global (see src/app.js, served at /data.js). The client-side
// picker (`t()` in public/app.js) falls back to Danish for any missing locale.
//
// Locales: da, en, de, fr, nl, sv, fi, no, pl, es, it, pt.
const PT = {
  da: {
    ttTitle: 'Trafiktyper',
    ttSubtitle: 'aggregeret for valgt periode',
    ttTotalRx: 'Total RX',
    ttTotalTx: 'Total TX',
    ttSplit: 'RX/TX-fordeling',
    ttPeakRx: 'Spids RX',
    ttPeakTx: 'Spids TX',
    ttTopTypes: 'Toptyper',
    ttNoBreakdown: 'Protokol-opdeling er ikke tilgængelig endnu',
    ttEmpty: 'Ingen trafikdata i den valgte periode',
    ttPrompt: 'Vælg en agent og hent data',
    ttLoading: 'Henter…',
  },
  en: {
    ttTitle: 'Traffic types',
    ttSubtitle: 'aggregated for selected period',
    ttTotalRx: 'Total RX',
    ttTotalTx: 'Total TX',
    ttSplit: 'RX/TX split',
    ttPeakRx: 'Peak RX',
    ttPeakTx: 'Peak TX',
    ttTopTypes: 'Top types',
    ttNoBreakdown: 'Protocol breakdown is not yet available',
    ttEmpty: 'No traffic data in the selected period',
    ttPrompt: 'Select an agent and load data',
    ttLoading: 'Loading…',
  },
  de: {
    ttTitle: 'Verkehrstypen',
    ttSubtitle: 'aggregiert für den gewählten Zeitraum',
    ttTotalRx: 'Gesamt RX',
    ttTotalTx: 'Gesamt TX',
    ttSplit: 'RX/TX-Verteilung',
    ttPeakRx: 'Spitze RX',
    ttPeakTx: 'Spitze TX',
    ttTopTypes: 'Top-Typen',
    ttNoBreakdown: 'Protokollaufschlüsselung ist noch nicht verfügbar',
    ttEmpty: 'Keine Verkehrsdaten im gewählten Zeitraum',
    ttPrompt: 'Wählen Sie einen Agenten und laden Sie Daten',
    ttLoading: 'Wird geladen…',
  },
  fr: {
    ttTitle: 'Types de trafic',
    ttSubtitle: 'agrégé pour la période sélectionnée',
    ttTotalRx: 'Total RX',
    ttTotalTx: 'Total TX',
    ttSplit: 'Répartition RX/TX',
    ttPeakRx: 'Pic RX',
    ttPeakTx: 'Pic TX',
    ttTopTypes: 'Principaux types',
    ttNoBreakdown: "La répartition par protocole n'est pas encore disponible",
    ttEmpty: 'Aucune donnée de trafic pour la période sélectionnée',
    ttPrompt: 'Sélectionnez un agent et chargez les données',
    ttLoading: 'Chargement…',
  },
  nl: {
    ttTitle: 'Verkeerstypen',
    ttSubtitle: 'geaggregeerd voor de gekozen periode',
    ttTotalRx: 'Totaal RX',
    ttTotalTx: 'Totaal TX',
    ttSplit: 'RX/TX-verdeling',
    ttPeakRx: 'Piek RX',
    ttPeakTx: 'Piek TX',
    ttTopTypes: 'Belangrijkste typen',
    ttNoBreakdown: 'Protocoluitsplitsing is nog niet beschikbaar',
    ttEmpty: 'Geen verkeersgegevens in de gekozen periode',
    ttPrompt: 'Selecteer een agent en laad gegevens',
    ttLoading: 'Laden…',
  },
  sv: {
    ttTitle: 'Trafiktyper',
    ttSubtitle: 'aggregerat för vald period',
    ttTotalRx: 'Total RX',
    ttTotalTx: 'Total TX',
    ttSplit: 'RX/TX-fördelning',
    ttPeakRx: 'Topp RX',
    ttPeakTx: 'Topp TX',
    ttTopTypes: 'Vanligaste typer',
    ttNoBreakdown: 'Protokolluppdelning är inte tillgänglig ännu',
    ttEmpty: 'Inga trafikdata för vald period',
    ttPrompt: 'Välj en agent och hämta data',
    ttLoading: 'Hämtar…',
  },
  fi: {
    ttTitle: 'Liikennetyypit',
    ttSubtitle: 'koottu valitulta ajanjaksolta',
    ttTotalRx: 'RX yhteensä',
    ttTotalTx: 'TX yhteensä',
    ttSplit: 'RX/TX-jakauma',
    ttPeakRx: 'Huippu RX',
    ttPeakTx: 'Huippu TX',
    ttTopTypes: 'Yleisimmät tyypit',
    ttNoBreakdown: 'Protokollajakauma ei ole vielä saatavilla',
    ttEmpty: 'Ei liikennedataa valitulta ajanjaksolta',
    ttPrompt: 'Valitse agentti ja hae tiedot',
    ttLoading: 'Ladataan…',
  },
  no: {
    ttTitle: 'Trafikktyper',
    ttSubtitle: 'aggregert for valgt periode',
    ttTotalRx: 'Total RX',
    ttTotalTx: 'Total TX',
    ttSplit: 'RX/TX-fordeling',
    ttPeakRx: 'Topp RX',
    ttPeakTx: 'Topp TX',
    ttTopTypes: 'Vanligste typer',
    ttNoBreakdown: 'Protokollfordeling er ikke tilgjengelig ennå',
    ttEmpty: 'Ingen trafikkdata i valgt periode',
    ttPrompt: 'Velg en agent og hent data',
    ttLoading: 'Henter…',
  },
  pl: {
    ttTitle: 'Typy ruchu',
    ttSubtitle: 'zagregowane dla wybranego okresu',
    ttTotalRx: 'Razem RX',
    ttTotalTx: 'Razem TX',
    ttSplit: 'Podział RX/TX',
    ttPeakRx: 'Szczyt RX',
    ttPeakTx: 'Szczyt TX',
    ttTopTypes: 'Najczęstsze typy',
    ttNoBreakdown: 'Podział według protokołów nie jest jeszcze dostępny',
    ttEmpty: 'Brak danych o ruchu w wybranym okresie',
    ttPrompt: 'Wybierz agenta i wczytaj dane',
    ttLoading: 'Ładowanie…',
  },
  es: {
    ttTitle: 'Tipos de tráfico',
    ttSubtitle: 'agregado para el período seleccionado',
    ttTotalRx: 'Total RX',
    ttTotalTx: 'Total TX',
    ttSplit: 'Reparto RX/TX',
    ttPeakRx: 'Pico RX',
    ttPeakTx: 'Pico TX',
    ttTopTypes: 'Tipos principales',
    ttNoBreakdown: 'El desglose por protocolo aún no está disponible',
    ttEmpty: 'No hay datos de tráfico en el período seleccionado',
    ttPrompt: 'Seleccione un agente y cargue los datos',
    ttLoading: 'Cargando…',
  },
  it: {
    ttTitle: 'Tipi di traffico',
    ttSubtitle: 'aggregato per il periodo selezionato',
    ttTotalRx: 'Totale RX',
    ttTotalTx: 'Totale TX',
    ttSplit: 'Ripartizione RX/TX',
    ttPeakRx: 'Picco RX',
    ttPeakTx: 'Picco TX',
    ttTopTypes: 'Tipi principali',
    ttNoBreakdown: 'La ripartizione per protocollo non è ancora disponibile',
    ttEmpty: 'Nessun dato di traffico nel periodo selezionato',
    ttPrompt: 'Seleziona un agente e carica i dati',
    ttLoading: 'Caricamento…',
  },
  pt: {
    ttTitle: 'Tipos de tráfego',
    ttSubtitle: 'agregado para o período selecionado',
    ttTotalRx: 'Total RX',
    ttTotalTx: 'Total TX',
    ttSplit: 'Divisão RX/TX',
    ttPeakRx: 'Pico RX',
    ttPeakTx: 'Pico TX',
    ttTopTypes: 'Principais tipos',
    ttNoBreakdown: 'A divisão por protocolo ainda não está disponível',
    ttEmpty: 'Nenhum dado de tráfego no período selecionado',
    ttPrompt: 'Selecione um agente e carregue os dados',
    ttLoading: 'Carregando…',
  },
};

module.exports = { PT };
